### ISSUE TITLE
Gestion formelle du complément sur Position

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/ban#108]
Suggestion issue de l'openlab du jour pour gérer les compléments d'adresse:

- rendre nullable la géométrie sur Position
- ajouter une colonne `name` comme pour les autres objets

Par exemple, l'entrée A du bâtiment B du 12 ter rue des Lilas serait modélisé de la sorte:
- "rue des Lilas" => Group
- 12 ter => HouseNumber pointant sur le Group "rue des Lilas" (`ter` ici est l'indice de répétition, colonne `ordinal`)
- bâtiment B => Position ayant pour `name` "bâtiment B", pointant sur le HouseNumber "12 ter"
- entrée A => Position ayant pour `name` "entrée A", pointant sur la Position "bâtiment B" et le HouseNumber "12 ter"

**Comment by cquest** [comment]
Dans ton exemple, l'entrée pointe seulement sur la Position "bâtiment B" qui elle même pointe sur le 12 ter qui elle même pointe sur Group, non ?

**Comment by yohanboniface** [comment]
> l'entrée pointe seulement sur la Position "bâtiment B" qui elle même pointe sur le 12 ter qui elle même pointe sur Group, non ?

Non, la clé étrangère de position vers housenumber est obligatoire en l'état.

**Comment by christopheprudent** [comment]
[cas des compléments d'adresse, de type sous-ensemble]

attention, il existe des compléments d'adresse sur des voies non numérotées
dans ce cas, elle est donc rattachée à la voie
l'astuce du housenumber avec number à NULL peut alors aussi aider à coder cet usage

**Comment by alahoule** [comment]
Et ton idée d'utiliser le Group pour les sur-ensembles Christophe ? Elle me semblait pertinente.

**Comment by christopheprudent** [comment]
[cas des compléments d'adresse, de type sur-ensemble]

pour cet usage (cas des ZI, des résidences qui contiennent elles-même des voies, ...), une solution serait de ranger ces compléments dans Group, avec peut-être le besoin de lier ses éléments fils (les voies)

là aussi, plusieurs solutions:
- lien réflexisf de la table Group
- utilisation de l'astuce du housenumber avec number à NULL (de la voie), rattaché alors à ce complément
