### ISSUE TITLE
La création d'un objet ne renvoie pas l'objet créé

### ISSUE THREAD

**Issue by jusabatier** [BaseAdresseNationale/ban#11]
Lors de la création d'un objet avec un POST, on s'attend à avoir une réponse contenant l'objet créé, afin de récupérer l'id de celui-ci.

Actuellement on a un code HTTP 201 et un corp de réponse vide.

**Comment by ebuard** [comment]
J'ai bien un corps de réponse:
{
"addressing": null,
"alias": [],
"attributes": null,
"created_at": "2019-04-09T13:12:59.660774+00:00",
"created_by": {
"client": "guichet",
"contributor_type": "ign",
"id": 939824,
"user": null
},
"fantoir": null,
"id": "ban-group-cd76ccee901e49e3b868efa05fecdc72",
"ign": null,
"kind": "way",
"laposte": null,
"modified_at": "2019-04-09T13:12:59.660774+00:00",
"modified_by": {
"client": "guichet",
"contributor_type": "ign",
"id": 939824,
"user": null
},
"municipality": "ban-municipality-0492ac474b144036a9e87a0bd87e9e37",
"name": "Toto",
"status": "active",
"version": 1
} 

Quel outil utilisez vous?

**Comment by jusabatier** [comment]
En effet, je viens de voir que ma methode ne recuperait le corp de requete que si le code HTTP etait 200.

Je ferme donc l'issue.

Merci
