### ISSUE TITLE
Impossible de créer une voiie sans FANTOIR

### ISSUE THREAD

**Issue by jusabatier** [BaseAdresseNationale/ban#12]
Il est impossible de créer une voie sans fournir de code fantoir.

En essayant on a une réponse HTTP 400 Bad Request.

Requete envoyée en POST : 
{"kind":"way","name":"Test de l'API","municipality":"ban-municipality-a1117d5b450043a9bb9fafebd405eb36"}

En envoyant la même requête avec un code fantoir, ça fonctionne : 
{"fantoir":"43157t002","kind":"way","name":"Test de l'API","municipality":"ban-municipality-a1117d5b450043a9bb9fafebd405eb36"}

Pourtant dans la description de l'API, le code FANTOIR n'est pas indiqué comme obligatoire.

**Comment by ebuard** [comment]
Bonjour.
Ma requête {  "municipality": "ban-municipality-0492ac474b144036a9e87a0bd87e9e37",  "name": "Toto",  "kind":"way"} fonctionne. Je n'ai pas fourni de fantoir. Quel outil de requête de l'APi utilisez-vous?

Par ailleurs, j'ai bien une réponse : 201 created
{
"addressing": null,
"alias": [],
"attributes": null,
"created_at": "2019-04-09T13:12:59.660774+00:00",
"created_by": {
"client": "guichet",
"contributor_type": "ign",
"id": 939824,
"user": null
},
"fantoir": null,
"id": "ban-group-cd76ccee901e49e3b868efa05fecdc72",
"ign": null,
"kind": "way",
"laposte": null,
"modified_at": "2019-04-09T13:12:59.660774+00:00",
"modified_by": {
"client": "guichet",
"contributor_type": "ign",
"id": 939824,
"user": null
},
"municipality": "ban-municipality-0492ac474b144036a9e87a0bd87e9e37",
"name": "Toto",
"status": "active",
"version": 1
}

**Comment by jusabatier** [comment]
Cela semble fonctionner à nouveau, je n'arrive pas à comprendre ce qui avait pu poser problème.

Désolé pour le dérangement.

**Comment by ebuard** [comment]
Pas de soucis! Je peux regarder avec vous.
