### ISSUE TITLE
Demander un token y compris pour le GET

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/ban#134]
Validé lors de la réunion téléphonique de ce jour.

**Comment by yohanboniface** [comment]
J'ai fait une première version, mais je laisse ouvert parce que je voudrais refactorer le code et passer par un middleware.

**Comment by yohanboniface** [comment]
Note: à partir de maintenant il faudra un token donc même pour les GET.
J'ai mis une note dans le README pour préciser comment créer un token pour le développement, et comment l'utiliser.

Dans la pratique, un exemple d'appel via httpie:

    http -b http://localhost:5959/group/fantoir:930010010/versions Authorization:"Bearer blablablabla"

**Comment by christopheprudent** [comment]
et pour l'accès ban-dev en ligne, comment fait-on ?

**Comment by yohanboniface** [comment]
Bonne question :)
Pour l'instant le code n'est pas déployé, je vous communiquerai un token via un "vrai" client quand ce sera déployé :)

**Comment by christopheprudent** [comment]
merci bien :+1:

**Comment by jpklipfel** [comment]
Bonjour comment obtenir un token pour tester ban-dev en ligne ?

**Comment by cquest** [comment]
Demande par mail à adresse@data.gouv.fr

**Comment by jpklipfel** [comment]
Ma demande du 9/08 11h13 est restée sans suite, quels seraient les critères pour obtenir ce token?

**Comment by yohanboniface** [comment]
C'est implémenté. On est passé sur Flask entre-temps, donc le concept de milddleware n'a plus cours. On est bon comme ça.

@jpklipfel le courriel est la marche à suivre pour ta demande, mais je crois que tous les voyants ne sont pas encore au vert pour distribuer des tokens.
Courriel @cquest si tu veux plus d'infos.

**Comment by jpklipfel** [comment]
Merci de la réponse, on va attendre que les voyants soient au vert
