### ISSUE TITLE
Ajout d'une classe complement d'adressage

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#135]
Ce ticket a pour but de discuter sur la faisabilité technique de la modélisation du complément d’adressage sous la forme d’une classe intermédiaire entre la classe « Position » et la classe «  House Number » :

![complement](https://cloud.githubusercontent.com/assets/16690380/16342157/f5470390-3a30-11e6-8453-a28c469aeda9.png)

Dans cette modélisation, il n’y a plus de lien de filiation entre Position. Celui-ci est reporté sur les compléments.
Un complément peut ne pas avoir de positions. Il peut aussi en avoir plusieurs.
Cela créé un lien cyclique. 
Quelles contraintes faut-il mettre sur ces liens ? Propositions :
-	Une position a forcément un house number.
-	Un complément a forcément un house number.
-	Une position doit pointer vers le même house number que son complément si elle en a un. 
-	Un complément doit pointer vers le même house number que son complement père s’il en a un. 

A quel niveau mettre ces contraintes (API, PostgreSQL) ?
Quels types pour la classe complément ? Si l’on regarde du côté d’INSPIRE, on retrouve cette notion dans la classe AddressLocator et plus précisément dans 2 énumérés : LocatorDesignator et LocatorName. 
La liste des valeurs possibles est :

**LocatorDesignator** :
+ addressIdentifierGeneral
+ addressNumber
+ addressNumberExtension
+ addressNumber2ndExtension
+ buildingIdentifier
+ buildingIdentifierPrefix
+ entranceDoorIdentifier
+ staircaseIdentifier
+ floorIdentifier
+ unitIdentifier
+ postalDeliveryIdentifier
+ kilometrePoint
+ cornerAddress1stIdentifier
+ cornerAddress2ndIdentifier

**LocatorName**:
+ siteName
+ buildingName
+ roomName
+ descriptiveLocator

En mixant les 2 et en mettant de côté les niveaux qui ne concernent pas les compléments, on pourrait proposer :
+ siteName
+ buildingName
+ buildingIdentifier
+ buildingIdentifierPrefix
+ entranceDoorIdentifier
+ staircaseIdentifier
+ descriptiveLocator (Narrative, textual description of the location or addressable object)

Si l’on croise avec les valeurs listées par Christophe dans l’issue 76 (https://github.com/BaseAdresseNationale/ban/issues/76), quelques propositions :
Pour le groupe 1, 
Entrée -> entranceDoorIdentifier
Hall -> entranceDoorIdentifier

Pour le groupe 2 :
Batiment -> buildingName ou buildingIdentifier
Tour -> buildingName ou buildingIdentifier
Allée -> ??
Villa -> buildingName
Bloc -> ?
Ilot -> siteName  ou à mettre dans group

Pour le groupe 3, cela serait plutôt à basculer dans les groupes ou siteName. Pour les résidences, siteName ou BuildingName

On peut aussi utiliser la valeur descriptiveLocator si on ne sait pas quoi mettre ou si on ne veut pas mettre en place la hiérarchie des compléments.

Faut-il mettre une contrainte sur la cohérence entre le type des compléments et le kind des positions (par exemple un Complément « entranceDoorIdentifier» peut-il avoir une position « building » ?) ? Je dirais plutôt non pour l’instant. Il faudrait d’abord être sûr des différentes valeurs possibles pour les 2 champs.  Faut-il mettre une contrainte ou lancer des contrôles réguliers sur la donnée ? Je serais plutôt partisan des contrôles pour l’instant.

Faut-il mettre une contrainte sur les types de compléments entre père et fils ? Je dirais plutôt oui mais quand on commencera à charger ces données avec des valeurs autres que siteName, buildingName, descriptiveLocator.

Quels comportements pour l’API ? :
-	Que doit renvoyer l’API si on demande toutes les positions d’un house number ?
-	Comment se comporte l’API quand on crée une position sur un complément (faut-il le rattacher directement au house number ou cela est-il fait automatiquement ?)
-	Idem quand on modifie le lien entre position  et complement ?
-	…

**Comment by yohanboniface** [comment]
Merci @odorie pour cet exposé détaillé de la proposition.
Comme je l'exprimais lors de notre point téléphonique, je suis personnellement frileux à aller dans cette direction, et je vais tâcher d'en exposer les raisons.

- d'abord, un point méthodologie, et ce n'est pas moi qui le répète à chaque bonne occasion: **«Ne cherchons pas à résoudre un problème qui n'existe pas»**. Personnellement, je vois pas à quel problème on cherche à répondre par cette proposition. Je ne vois aucun cas d'adresse qui ne marcherait pas dans la modélisation actuelle et que cette proposition rendrait possible. On a au mieux une solution plus complexe pour répondre à un même besoin. Et même plutôt une solution plus limitée, voir ci-dessous.
- toujours sur la méthodologie: cette proposition avait été exposée lors d'un *openlab*, mais avait été écartée. **L'*openlab* n'est certes pas une instance de validation, mais c'est clairement le seul et unique moyen en l'état d'obtenir du feedback de la part de nos futurs clients.** Or, le feedback, en méthode agile tout au moins, c'est l'essence de l'arbitrage. **Je suis mal à l'aise d'en prendre le contre-pied.** Il faudra a minima l'exposer clairement lors du prochain *openlab*, en gardant la souplesse pour prendre en compte les retours collectés. Mais c'est pour moi une **alerte sur notre fonctionnement agile.**
- sur la modélisation elle-même: un argument qui est avancé pour justifier une classe `Complement` est de séparer l'information géographique de l'information sémantique. Or, **en ayant, et en conservant, une colonne `kind` on a déjà une information sémantique sur `Position`**: `kind=building`, `kind=entrance`, etc.
- sur la modélisation toujours: le schéma présenté ici perd la possibilité de créer des liens de filiation entre `Position`. **Quand il n'y aura pas de `Complement`, c'est-à-dire dans la très grande majorité, on ne pourra pas établir que telle `Position` de type "postbox" est fille de tel "building"** (et pas d'un autre). Et je ne pense pas qu'on veuille s'enfoncer au point d'avoir une relation hiérarchique dans `Complement` ET dans `Position`.
- en créant une nouvelle classe que l'on doit par la force des choses typer aussi, **on dénormalise les données**: par exemple, un bâtiment va se trouver qualifié comme "building" à la fois dans la classe `Complement` et dans la classe `Position`. La dénormalisation est à éviter autant que possible, et quand on y souscrit ce doit être assumé et étayé.
- on a avancé en fin de réunion téléphonique que le split de `Position` en deux classes distinctes faciliterait la validation des données («coups de tampon»). D'une part, c'est un argument justificatif a posteriori qui doit être à mon avis éliminé pour cette seule raison (on a dit dans la même réunion, concernant les compléments de type `Group`, que la validation n'était pas la question). Surtout, **en ayant dénormalisé la donnée, on va certes pouvoir valider plus facilement les `Complement` d'une part et les `Position` de l'autre, mais sans aucun moyen de tamponner la cohérence des deux** (une `Position` de type "building" associée à un `Complement` de type "staircase"…).
- la dénormalisation a aussi pour conséquence une **relation cyclique** `Position<->HouseNumber<->Complement` (et @odorie l'a exposé); la seule expression de «relation cyclique» devrait nous faire reculer à mon sens (ce ne serait pas la seule dans la modélisation, mais ce n'est pas une raison pour en ajouter).
- globalement, **la dénormalisation va nous obliger ou bien à ajouter des règles métier complexes et contraignantes à outrance, ou bien à avoir des données incohérentes**. Prenons un cas tout bête, mettons qu'on veuille empêcher un `Complement` et une `Position` qui sont associés d'avoir un `HouseNumber` parent différent. Si on met un check au moment du `save` de chaque objet, on ne pourra plus changer le `HouseNumber` de ces objets: au moment du `save` du premier des deux objets, une erreur sera levée pour incohérence. Ce serait la même chose si on voulait valider la cohérence des `kind` entre les deux classes. Bien sûr on peut décider de déléguer ça au monitoring, mais ça revient à rajouter du bruit inutile dans une étape cruciale. **Rendre le monitoring inutilement bruyant c'est le tuer dans l'œuf.** On pourrait aussi mettre en place des validations de schéma par lot, mais veut-on complexifier autant le code, et s'enfoncer dans les coûts de maintenance future?
- en résumé, **il est pour moi très important de rester dans un cadre simple, cohérent avec le modèle de fonctionnement collaboratif de la future base**. Avoir un modèle compliqué, qui demande une connaissance subtile, va engendrer des incohérences très rapidement par méconnaissance du modèle. Plus globalement, **déroger au KISS, c'est s'exposer aux coûts cachés de la maintenance**: plus de support pour expliquer comment fonctionne le modèle, donc une documentation plus chargée et moins invitante; une API plus difficile à utiliser, donc plus de support technique; dénormalisée, donc plus difficile à gérer, garder les données en cohérence; donc plus de code, donc plus de coût de maintenance évolutive, etc.

Pour rappel, ma position (huhu): il faut voir la `Position` comme **une représentation physique de l'adresse, qui peut ou non être nommée, et dont on connaît ou non la position géographique**; il faut peut-être étendre les `kind` valides pour `Position` de sorte à couvrir tous les cas identifiés ici.

Je pense donc qu'en allant dans cette direction, on dégrade le modèle, et ma recommandation est donc de ne pas la suivre.
Je ne remets pas du tout en question la bonne foi de la proposition, mais je pense, *sincèrement,* qu'elle ne résiste pas à un examen plus approfondi.
J'ai bien conscience de l'enjeu "politique" derrière ce point d'achoppement, et moi aussi je ne demande qu'à nous mettre tous d'accord sur le modèle, qu'on puisse avancer, tous ensemble. Mais je crois agir en professionnel en exposant ici les problèmes que je vois à suivre la proposition présentée.

Maintenant, ceci étant exposé au bon sens collectif, et j'ai moi-même rappelé cette règle récemment, il revient au coordinateur technique de trancher les différends sur les points techniques (ou au COPIL en dernier recours, on l'a dit, mais tâchons de ne pas demander à des non-techniciens de trancher des points techniques…). Je me plierai à la décision. @cquest à toi la parole, donc.

**Comment by odorie** [comment]
Quelques éléments supplémentaires :

-	les 3 modèles, discutés jusqu’à présent, permettent de stocker les données, avec chacun des avantages/inconvénients. Quelques avantages de ce modèle :
o	la solution proposée permet de séparer les différents concepts : du coup par exemple, l’IGN pourrait valider uniquement les positions sans valider les compléments ; La Poste pourrait valider les compléments uniquement… 
o	Ce modèle permet aussi de ne pas dupliquer un complément avec plusieurs positions : par exemple si le bâtiment A a plusieurs positions, le complément « Bâtiment  A» ne sera répété qu’une seule fois 
o	Ce modèle essaye de normaliser les compléments ce qui devrait permettre à terme de mieux les mettre à jour/contrôler. 
 
-	Le champ kind sur Position est certes une information sémantique mais il permet de caractériser la géométrie. Ce champ n’a pas de de sens sans géométrie. Ce n’est pas le cas du complément d’adressage qui peut se passer de géométrie et n’apporte pas d’informations sur la géométrie même.

-	Pour moi, le lien de filiation n’a que peu d’intérêt sur les géométries pures (sans complément donc). Des positions qui possèdent un lien de parenté ne font pas sens sans aucune sémantique.

-	Le champ type sur complément n’est pas redondant avec le champ kind de Position. Un complément de type « Bâtiment » pourra avoir des positions de kind « Building », « Staircase ».  je ne suis pas sûr qu’il faille mettre des contrôles/contraintes sur ce point. Avec le modèle « complément d’adressage » sur position, la question des contrôles entre le complément d’adresse et le kind de position se pose aussi. 

-	 Dans la plupart des cas, l’utilisateur n’utilisera pas les compléments d’adressage et pour lui l’API ne devrait pas être plus complexe à utiliser. Par contre si il souhaite mettre à jour/utiliser les compléments, l’API sera moins facile à utiliser ou l’utilisateur devra respecter plus de contraintes. Mais les données seront plus propres.

-	Comme tu le dis, ce modèle va obliger à ajouter des règles supplémentaires dans l’API / Base de données. Nous pourrions peut-être prévoir un point téléphonique pour échanger sur ce point et voir quelles sont les différentes possibilités. L’IGN propose aussi de proto-typer l’API avec ce modèle  et avec vous.

**Comment by christopheprudent** [comment]
quelques arguments sur la séparation en 2 de l'entité `Position`

- la hiéarchie sur `Position` ne me semble pas liée à la géolocalistion, mais en effet plutôt portée par l'organisation des "structures" d'un complément d'adresse, et donc le besoin d'une nouvelle Ressource `Complement` indépendante
/ex : une résidence contient des bâtiments, qui eux-mêmes peuvent disposer de plusieurs entrées
par contre, à chacun des ces éléments d'adresse peut être associé 1 ou plusieurs types de géométrie (**entrance**, **postal**, ...)

- et pour reprendre cette idée d'association, de manière plus générale, une géométrie vient enrichir la sémantique d'un élément d'adresse, en précisant le lieu (x, y)
cette association, dans le modèle, limitée aux niveaux (`Housenumber`, voir `Group` via l'artifice Number à NULL) peut être généralisée à tous les niveaux, ce qui là aussi tend à isoler cette Resource

- le nommage de la Ressource actuelle `Position` peut apporter des confusions sur son contenu, dans le cas d'une hiérarchie de compléments, alors que ceux-ci ne possèdent pas de géométrie (comme c'est le cas dans le référentiel postal)

**Comment by yohanboniface** [comment]
> la hiéarchie sur Position ne me semble pas liée à la géolocalistion, mais en effet plutôt portée par l'organisation des "structures" d'un complément d'adresse, et donc le besoin d'une nouvelle Ressource Complement indépendante

> le lien de filiation n’a que peu d’intérêt sur les géométries pures (sans complément donc).

Sous-entendez-vous que dans les 98% des cas où les adresses sont sans complément on aura pas de possibilité de modéliser la hiérarchie de leurs entités?

J'insiste sur un point: dans la modélisation actuelle, `Position` ne représente pas strictement une position géographique, mais une **représentation physique de l'adresse**, là où `HouseNumber` correspond strictement à sa **définition administrative**.
Dès lors, on veut pouvoir **qualifier sémantiquement ces "représentations physiques"** même lorsqu'elles n'ont pas de nom (i.e. même si elles ne consistent pas en un *complément nommé* de l'adresse), c'est-à-dire définir si ces "représentations physiques" sont un bâtiment, une boîte aux lettres, une entrée, etc. Et c'est bien le rôle de sa propriété `kind`.
**Ces "représentations physiques" peuvent ensuite avoir un nom, ou pas.**
Peut-être faut-il renommer `Position` en `Localization` pour aider à lever cette ambiguïté? Ou `Implantation` (pas sûr du mot anglais pour ça)?

> par exemple si le bâtiment A a plusieurs positions, le complément « Bâtiment A» ne sera répété qu’une seule fois

D'après moi, on ne veut pas que le "bâtiment A" ait plusieurs positions géographiques *per se*. On veut que l'adresse administrative puisse avoir plusieurs "représentations physiques", une pour le bâtiment, une pour la boîte aux lettres, une pour chaque bâtiment s'il y en a plusieurs, etc. Mais pour chacune de ces "représentations physiques", on veut converger. Sinon, si chacun peut avoir sa propre position pour une même entité physique, BAN c'est pas "Base adresse nationale", mais "Bazar des adresses national" :p

Ici un message subliminal:
*Simplicité, simplicité, simplicité.*

:)

**Comment by christopheprudent** [comment]
je n'avais pas bien perçu `Position` qui pour moi avait un sens de géolocalisation uniquement :smirk:
peut-être à renommer alors, mais à trouver plus signifiant ???
alors, pour la simplicité, carrément `Position` devient `Complement`, bon je :smile:
mais plus en lien avec la réalité Terrain...

**Comment by cquest** [comment]
Quelques remarques:

- **kind** sur `Position` permet de décrire la position (c'est quoi), pas la géométrie en elle même où l'on devrait plutôt avoir une description sur le "comment" que l'on a dans les attributs (positionning)... et depuis la dernière itération (openlab 4) la géométrie peut être nulle (X/Y inconnus), **kind** décrit donc bien autre chose que la géométrie elle même.
- **kind** devrait s'approcher des valeurs INSPIRE listées par @odorie pour faciliter les échanges INSPIRE, entièrement d'accord là dessus.
- au delà de la seule gestion des compléments postaux, on a à plusieurs reprise lors des openlab ouvert la porte au partage de positions détaillées un peu plus "métier" (vanne d'arrêt de gaz, points pour les secours, etc) mais utiles à partager. La BAN avec son API de gestion est un outil qui vise un peu plus large que la seule alimentation des SI IGN et SNA.
- un "libellé" Poste sur `Position` permet d'avoir le libellé postal du complément, exemple: kind=entrance, ref=A, laposte="ENTREE A"

Après (longue) réflexion, je préfère finalement aussi le modèle plus simple, non cyclique, qui me semble plus facile à appréhender et à maintenir dans l'immédiat.

La volumétrie de données est limitée, 700 000 compléments dans les données SNA actuellement.
Il sera toujours possible de refactoriser ça si le besoin s'en fait vraiment sentir... et pour l'instant on ne sait même pas si le SNA va verser ces données dans la BAN (et cette question n'est pas liée au modèle à ce qu'il me semble).

C'est le double lien de `Position` vers `Housenumber` et `Complement` qui me pose le plus de problème dans cette proposition.
Ce lien cyclique est vraiment problématique et va par exemple générer des millions et des millions de liens nuls vers `Complément` (et qui le resteront), là où il me semble préférable d'avoir quelques `Position` sans géométrie (au démarrage mais qui se rempliront à terme car on espère pouvoir attribuer une position aux compléments).

**Comment by ebuard** [comment]
Je pense que notre définition de l'adresse n'est pas identique. Il faudrait peut-être commencer nos échanges par ça.

Pour moi, HouseNumber était tout _simplement_ la classe d'adresse sémantique et la Position, la classe géographique. J'imaginais dans cette optique que le complément était sémantique, sans notion géométrique. Pour vous, l'adresse se découpe en représentation administrative et physique. Le complément aide donc pour vous à distinguer les notions physiques d'une adresse. Ainsi "Bâtiment B" aide à déterminer une position. En gros, le complément servirait à passer d'une position nulle avec complément à une position non nulle. C'est moins _simple_.

Ma vision facilitait les validations (divers organismes validaient une classe) et les droits d’édition des données. 
- S'il  n'y a pas cette dichotomie, pourquoi ne pas les mettre ensemble?
Les compléments ne sont, eux, pas validables, parce qu'il n'y a aucune instance responsable de leur validation. Donc ils peuvent l'être par tout le monde.
Doit-on pour autant faire valider par tout monde Position, HouseNumber et les deux en même temps?
- Si on  mêle les compléments à d'autres classes, faut-il faire des validations par champs et non par classes?
- idem pour les droits d'édition?
Ça complique les règles de vie de la BAN. Et du coup, ça va dans le sens où il faut bien formaliser ces règles.


Sur le fond, je pense qu'il pourrait y avoir plusieurs positions par adresse (bâtiment, parcelle, entrée...) et pas forcément converger vers une adresse. En effet, les gestionnaires de réseaux ou les pompiers veulent avoir une position particulière de l'adresse. C'est d'ailleurs ce qui est implémenté dans INSPIRE, ce qui permettra de recevoir des données INSPIRE plus facilement.

**Comment by yohanboniface** [comment]
Je ferme ici, je pense pas qu'on revienne sur ce thread.
On ouvrira un nouveau ticket si on doit adapter la modélisation.
