### ISSUE TITLE
Test base de données

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/ban#142]
En vue de faire des remontées sur la base de données BAN chargée, pouvez-vous me fournir un lien ou un moyen pour tester cette base?

Merci.

**Comment by yohanboniface** [comment]
Je t'envoie ça par mail.

**Comment by yohanboniface** [comment]
Ah mais non je suis bête on l'a mis sur la doc (présentée lors du dernier openlab):

http://adresse.data.gouv.fr/api-gestion/

**Comment by ebuard** [comment]
Je vois qu'il y a une doc sur l'API, ce qui est utile.
Je reprends ma question initiale: comment a t-on accès à la base initialisée? Je ne vois aucune information concernant la base sur cette doc.

Et comme tu as renvoyé la doc sur l'API, je me demande si tu veux qu'on utilise l'API pour faire des contrôles sur la base?

**Comment by ebuard** [comment]
BUT : recetter le contenu + déployer hébergement

**Comment by yohanboniface** [comment]
> Et comme tu as renvoyé la doc sur l'API, je me demande si tu veux qu'on utilise l'API pour faire des contrôles sur la base?

Ce serait un moyen de faire une pierre de coups: tester les données ET l'API.

> nous aimerions avoir accès à un dump complet de la base de données initialisée mi-juin

@cquest je peux faire le dump, mais je sais pas ensuite comment ça se passe pour les accès au serveur pour qu'ils puissent le télécharger. Je le mets derrière Nginx et roule ma poule pour cette fois?

> Pouvez-vous aussi nous renvoyer le nouveau dump quand la base sera réinitialisée avec les données envoyées vendredi dernier ?

Absolument! Mais ça va prendre un peu de temps. Selon les estimations du dernier run, il faut 4 jours pour importer toutes les données.

> Pouvez-vous nous donner l'accès aux scripts d'initialisation ?

Une question pour @cquest, je sais pas précisément quels scripts de ban-data/bano sont utilisés.

**Comment by christopheprudent** [comment]
ce besoin de récupérer une image de la base initialisée (dump) l'est aussi pour LA POSTE
tu avais par contre mentionner un "souci" de volume (120 Go) :grimacing:

**Comment by cquest** [comment]
dump en cours...
