### ISSUE TITLE
Ajouter un champ de type daterange sur Version

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/ban#145]
A mettre à jour au moment de la création d'une version et au moment de la création de la version suivante.
Ajouter aussi la possibilité de demander la version d'un objet à une date donnée via l'API.

**Comment by yohanboniface** [comment]
Pour le nom de la colonne: "range", "period", "validity", "from_to"…

**Comment by christopheprudent** [comment]
"period" me semble bien

**Comment by yohanboniface** [comment]
J'étais parti pour ajouter un index 'model_name', 'model_pk', 'period', mais il me semble qu'on va seulement utiliser "period" pour demander la version d'un objet à une date en particulier, et on a déjà un index sur 'model_name' et 'model_pk', et comme on aura jamais mille versions pour même objet, j'ai l'impression que l'index est inutile. Des avis?

**Comment by christopheprudent** [comment]
ok avec toi, le peu d'occurences de version pour un même objet limite l'intérêt d'un index spécifique (voir dégrade l'accès aux données, en cas de mises à jour, qui au total seront elles en volume important)

**Comment by yohanboniface** [comment]
Après enquête, je crois qu'on veut un type `tsrange` et pas `daterange`. Criez si je me fourvoie ;)

Doc: https://www.postgresql.org/docs/9.5/static/rangetypes.html

**Comment by christopheprudent** [comment]
la différence est liée à l'inclusion de l'heure dans le timestamp par rapport à celui lié à la date, non ?

**Comment by yohanboniface** [comment]
Oui, date vs datetime, et nous on veut sans timezone, parce qu'on est tout en UTC.

**Comment by yohanboniface** [comment]
Anecdote du jour:

«The official abbreviation for Coordinated Universal Time is UTC. This abbreviation arose from a desire by the International Telecommunication Union and the International Astronomical Union to use the same abbreviation in all languages. English speakers originally proposed CUT (for "coordinated universal time"), while French speakers proposed TUC (for "temps universel coordonné"). The compromise that emerged was UTC.»

(Dnas la rubrique «Toi aussi instruis-toi en bossant sur la BAN» ;) )

**Comment by christopheprudent** [comment]
excellent :smile:
