### ISSUE TITLE
Store metadata classes in the MCD

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/ban#15]
An idea in the BAN MCD: create metadata classes, as it is important, containing versions, sources, dates and linked to different existing classes: HouseNumber and Position.
What about the "lieux-dits"? A zone as well contained in Locality and having an Adress?
From that, I suggest to rename HouseNumber to Adress since a "lieux-dits" can have an adress, not only a house....

**Comment by yohanboniface** [comment]
> An idea in the BAN MCD: create metadata classes, as it is important, containing versions, sources, dates and linked to different existing classes: HouseNumber and Position.

We already have metadata (create_by/at, modified_by/at, version) on each class. Maybe source can be added, but an object usually have multiple sources.
Am I missing something else from your suggestion?

> From that, I suggest to rename HouseNumber to Adress since a "lieux-dits" can have an adress, not only a house....

Good point :) Though, I think "Address" means the concatenation of number, street, zipcode, etc., so I'm not sure that's the best candidate. What about "PlaceNumber", at this point?

**Comment by yohanboniface** [comment]
Je ferme ici en faveur de #42.
