### ISSUE TITLE
Doc d'installation de l'API en environnement de production

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#151]
Une doc d'installation pour un environnement de développement existe actuellement dans le readme.
Pourriez-vous la compléter avec une doc d'installation pour un environnement de production ?
(L'IGN utilisera cette doc pour déployer une instance de l'API)

**Comment by yohanboniface** [comment]
https://github.com/BaseAdresseNationale/ban/wiki/Tutorial-d'installation-sur-un-serveur-de-production

Mais pas encore eu le temps de la tester, donc à prendre avec des précautions pour l'instant ;)

Est-ce que c'est utile si j'en fais un script Ansible?

**Comment by odorie** [comment]
Merci pour le tuto.
On va le tester dans les prochains jours.
Nous reviendrons vers toi si besoin.
