### ISSUE TITLE
récuparation des objets dans une boîte englobante

### ISSUE THREAD

**Issue by lfraval** [BaseAdresseNationale/ban#155]
Bonjour à tous,

Existe-t-il dans l'API un moyen de récupérer des objets contenus dans une boîte englobante ?

Merci d'avance,
Cdt

**Comment by yohanboniface** [comment]
C'est possible pour les HouseNumber et les Position (qui ont un  champ géographique), via les paramètres `north`, `south`, `east`, `west`, permettant de définir la bbox.

Par exemple:

    http://localhost:5959/housenumber?north=1&south=0&west=0&east=1
