### ISSUE TITLE
Prise en compte des modifications des communes dans le modèle lors de fusion de communes

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/ban#168]
En raison des fusions de communes, certaines communes sont des communes déléguées (équivalentes au lieu dit) et le courrier n'arrive plus aux habitants de communes fusionnées, sans parler des impôts, EDF... Or les communes déléguées ont une existence de la part de l'état mais pas dans les base de données.
Je ne sais pas si nous en avions parlé lors d'un openlab.
Nous n'avons pas étudié cette question: Comment stocke t'on cette information dans le modèle BAN?
Il faut absolument faire apparaître le nom de la commune déléguée. Crée t'on un nouveau champ sur Muncipality ou utilise t'on Group? Qu'en est-il des bases La Poste et l'INSEE? Y avait-il des normes à appliquer sur ce champ: des parenthèses, une norme afnor?
Si on ne fait rien, il faut absolument faire apparaître cette information dans les exports BAN pour que les organismes puisse utiliser cette information.

Elodie

**Comment by ebuard** [comment]
Et je me pose aussi la question des nouvelles régions: faut-il les faire apparaitre dans le modèle, dans les alias de municipality par exemple?

**Comment by yohanboniface** [comment]
Doublon de #62 je pense.

**Comment by ebuard** [comment]
Non. La #62 parle du stockage des anciens noms de communes.
Je parle ici de stocker le nom de la **commune déléguée**, ce qui est réglementaire. Nous n'avons pas cette information: chaque commune est indépendante des autres. Autrement dit, il s'agit de créer soit un nouveau champ sur Municipality identifiant la commune déléguée. soit une hiérarchie sur Municipality, une municipality référençant une autre municipality, qui est sa commune déléguée.

**Comment by ebuard** [comment]
Je suppose que la poste a le même problème...

**Comment by yohanboniface** [comment]
Il me semble que #62 décrit la solution: utiliser des objets Group (District à l'époque).
Ce n'est pas suffisant?

**Comment by ebuard** [comment]
une simple question; à l'heure actuelle, quelles requêtes fais-tu pour connaître la commune déléguée d'une commune qui a fusionnée?

**Comment by cquest** [comment]
En interrogeant les groups de cette commune nouvelle, dedans on retrouvera un groupe pour chaque commune déléguée, et chaque groupe permettra de retrouver les adresses qui s'y trouvent.

On peut mettre en attribut sur le groupe correspondant à une commune déléguée des infos comme son code INSEE disparu. Si on cherche par contre une municipality par code INSEE qui correspond à une commune maintenant déléguée, le mécanisme de redirection renverra un pointeur vers la commune nouvelle qui l'a remplacée.

Ce n'est certes pas un accès direct, mais modéliser plus en dur ces entités ne me parait pas souhaitable pour le long terme.
Le législateur est créatif... après les communes simple, associées, nouvelles et déléguées, on aura sûrement d'autres status. La BAN n'est pas non plus un outil destiné à gérer cela, tout comme les autres niveaux administratifs.
Il faut qu'on ait les infos pour gérer correctement les adresses lors de ces évolutions, et il me semble qu'on a tout ce qu'il faut, non ?
