### ISSUE TITLE
Retour des positions dans une application Carto au format GeoJSON + données étendues

### ISSUE THREAD

**Issue by lfraval** [BaseAdresseNationale/ban#176]
Bonjour,

Dans le cadre de nos tests sur l'API BAN, nous essayons de faire afficher/consulter les points adresses de la ban dans une page web avec OL3.

Du coup pour répondre à ce besoin, nous proposons d'ajouter ou de modifier une fonctionnalité qui, à partir d'une bbox en entrée, renverrait une feature collection de positions. Chaque position aurait les caractéristiques suivantes :
- elle serait en [GeoJson](http://geojson.org/geojson-spec.html).
- elle contiendrait un minimum d'informations des objets associés (les informations du housenumber, le nom du group, le code postal, commune).

Cette nouvelle route de l'API pourrait être réutilisée par nos partenaires avec une librairie cartographique.

Le paramètre BBOX serait du style:
`&bbox=ouest,sud,est,nord`
Exemple:
`&bbox=5.0491,43.4033,5.0575,43.4077`
Et le résultat attendu serait du style:
 ```
 { "type": "FeatureCollection",
    "features": [
      { "type": "Feature",
          "geometry": {"type": "Point", "coordinates": [-0.499566,44.923783]},
          "properties": {
            "ign": null,
            "source": null,
            "housenumber": "ban-housenumber-cdf214b24dae4744b4ace68f9b22f6ca",
            "name": null,
            "kind": "entrance",
            "positioning": "other",
            "housenumber": {
              "ign": "ADRNIVX_0000000327012776",
              "modified_by": {
                "user": "idc",
                "client": null,
                "id": 6
              },
              "created_by": {
                "user": "idc",
                "client": null,
                "id": 6
              },
              "cia": "33003_0207_0_",
              "number": "0",
             
              "laposte": null,
              "created_at": "2016-08-08T11:56:14.181294",
              "version": 1,
              "postcode": {
                "code": "33440",
                "resource": "postcode",
                "attributes": null,
                "id": "ban-postcode-bc7ec52d278d4c7bb26337acf398d99d",
                "name": "Ambarès-et-Lagrave",
                "municipality": "ban-municipality-34d5a6662716490e9104d7ceb242bde1"
              },
              "attributes": null,
              "ancestors": [],
              "modified_at": "2016-08-08T11:56:14.181294",
              "parent": {
                "ign": null,
                "addressing": null,
                "resource": "group",
                "attributes": null,
                "laposte": null,
                "alias": null,
                "municipality": "ban-municipality-34d5a6662716490e9104d7ceb242bde1",
                "name": "Avenue de l'Europe",
                "id": "ban-group-d49d1e50eec443cb9cfc9e803b2a5f3a",
                "kind": "way",
                "fantoir": "330030207"
              },
              "ordinal": null,
              "id": "ban-housenumber-cdf214b24dae4744b4ace68f9b22f6ca"
            }
          }
        },
        { "type": "Feature",
          "geometry": {"..."},
          "properties": {"..."}
        }
       ]
     }
```
Merci de votre retour.

**Comment by christopheprudent** [comment]
je trouve l'idée super :+1:

**Comment by MaelREBOUX** [comment]
De même :+1: 

pour l'ordre des coordonnées de la bbox je conseille de s'aligner sur l'ordre du WMS 1.3.0

**Comment by yohanboniface** [comment]
Je vois deux sous-proposition dans ce ticket:
- d'une part, avoir une collection d'objets Position au format GeoJSON
- d'autre part avoir une représentation étendue des relations n et n+1 dans cette même collection

Je suis assez convaincu par le point 2, mais moins par le premier. Le format GeoJSON ne s'adapte qu'à la resource Position (puisque c'est la seule qui a une notion géométrique), et je suis pas sûr que ce soit une bonne idée d'introduire un format spécifique. Je pense qu'il est préférable de garder l'API cohérente.
D'autant qu'on est ici dans les cas d'une API de gestion, pas de consultation, donc pour moi il est plus important d'être sûr que les représentations des resources exposées sont dans le format qu'on accepte aussi en entrée.
Par ailleurs, le GeoJSON n'est jamais qu'un json normé, et il est très facile pour un client de passer du json fournit par l'API BAN  un GeoJSON, ou tout simplement de consommer directement ce même json.
Mais je peux rater un truc, et suis bien sûr preneur d'arguments contraires :)

Je suis pas certain du cas d'usage derrière la demande, mais ma proposition c'est plutôt d'attaquer via le endpoint d'une collection de HouseNumber, qui permet aussi de filtrer via une bbox. Ce endpoint étant à 1 distance à la fois de Position et de Group, et permettant aussi d'avoir les Position groupées par HN du coup.
Et c'est là que le point 2 de la présente proposition prend tout son sens. Je vais réfléchir à un moyen d'avoir les relations étendues, sans pour autant que ce soit le cas par défaut (coûteux).

> pour l'ordre des coordonnées de la bbox je conseille de s'aligner sur l'ordre du WMS 1.3.0

On a mis des paramètres séparés (north, south, etc.) justement pour éviter cette prise de tête permanente dans le monde SIG.

**Comment by ebuard** [comment]
Bonjour.

Nous avons déjà expliqué nos arguments concernant ces deux besoins (format + ressources étendus) : 

- ils sont nécessaires pour brancher le guichet adresse à la BAN.

- ce sont des standards de la géomatique, et donc peuvent servir à d'autres partenaires, voire pour développer des plugins dans logiciels libres de SIG, comme QGIS.

Ces deux besoins sont incontournables; le prototypage du branchement du guichet est en suspend en attendant la résolution de ce ticket. 
Nous avons compris que vous (Etalab) ne souhaitiez pas développer cette partie dans l'API de gestion. Nous (IGN) proposons de développer une route spécifique dans l’API BAN de gestion, comme suggéré par Ludovic (format + ressources étendues), ce qui nous permettra de contribuer à l’API. Ceci sera utile à nous et à tous les utilisateurs qui auraient un besoin similaire. Dans ce cas, nous vous remercions par avance des questions qu'on pourra vous poser sur l'API et du fork de notre code dans l'API.

En parallèle, tu parles, Yohan, d'API de consultation. Or d'une part cette API n'a pas de contour très clair avec l'API de gestion: dans l'API de gestion, il y a des fonctions de diffusion. Il faudrait définir les comportements, les contributions et les utilisations des deux API. D'autre part, techniquement, nous ne connaissons pas le fonctionnement de cette API de consultation. Par exemple: est-elle branchée  sur la base BAN maître?

Nous avons besoin de votre avis rapidement. Nous ferons le point à la prochaine réunion BAN Team, lundi.

**Comment by yohanboniface** [comment]
> Nous avons compris que vous (Etalab) ne souhaitiez pas développer cette partie dans l'API de gestion. 

C'est pas tout à fait ça, la gestion des ressources étendues est une demande tout à fait légitime, et elel est en cours de réflexion/résolution ici #183.
Je (Yohan) pense juste qu'avoir du GeoJSON sur un seul endpoint n'est pas très cohérent ni très adapté pour une API de gestion. Le principe actuel c'est que la resource telle que l'API la sert est au bon format pour la renvoyer à l'API. Si on sert du GeoJSON, ça ne sera pas le cas, il faudrait donc consommer selon un certain format, et renvoyer selon un autre format, ce qui me semble beaucoup plus compliqué côté client.

> Nous (IGN) proposons de développer une route spécifique dans l’API BAN de gestion, comme suggéré par Ludovic (format + ressources étendues)

Comme dit plus haut, c'est en cours pour les ressources étendues. Pour le format, vraiment, je pense que ce serait beaucoup moins de boulot pour vous de consommer le json tel quel côté client, quitte à la transformer à la volée en GeoJSON pour l'affichage sur une carte. Mais c'est l'affaire de 6 lignes de JS.

> D'autre part, techniquement, nous ne connaissons pas le fonctionnement de cette API de consultation.

A ma connaissance, il n'y pas d'API de consultation. Il y a des exports sous forme de dumps (actuellemement un seul format mais ça évoluera sûrement). Et éventuellement des services qui consomment ce dump pour fournir des APIs, par exemple addok.

**Comment by cquest** [comment]
Le récupération des données par bbox est quand destinée aux clients pour faciliter l'accès global au données destinées à l'édition... par à la "consommation" des données de la BAN.
La question ici est avant tout la charge que les abus pourraient générer sur l'API... à voir à l'usage.

**Comment by yohanboniface** [comment]
Je ferme ici, a priori aucune autre action n'est attendue.
