### ISSUE TITLE
Group: Non remplissage du champ addressing sur les groupes lors de l'initialisation de la BAN

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#177]
Le champ addressing des groupes est vide dans la BAN initialisée fin août.
Ce champ est fourni dans les exports du SGA/BDUNI de l'IGN : champ type_d_adressage du fichier ban.group<dep>. 
Dans ce fichier, les différentes valeurs possibles de ce champ sont :
-      vide ou null
-	Classique
-	Mixte
-	Linéaire
-	Anarchique
-	Métrique

Les différentes valeurs attendues dans la ban sont décrites dans le ticket #98 (passage en anglais des valeurs du csv)

**Comment by yohanboniface** [comment]
J'ai ajouté la prise en charge dans le code, reste à le mettre dans les données :)

**Comment by cquest** [comment]
C'est en principe réglé dans l'init du 21-09-2016... je passe le relais.

**Comment by odorie** [comment]
Je confirme que c'est bon dans le dernier dump du 21/09. Je ferme le ticket.
