### ISSUE TITLE
Non remplissage du champ ign sur les groupes lors de l'initialisation de la BAN

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#178]
Le champ ign (identifiant IGN) des groupes est vide dans la BAN initialisée fin août.
Ce champ est fourni dans les exports du SGA/BDUNI de l'IGN : champ id_pseudo_fpb du fichier ban.group<dep>.

**Comment by yohanboniface** [comment]
@cquest je crois pas avoir de fichier "group" dédié ?

Par ailleurs, j'avais compris que l'IGN n'avait pas d'id de group, mais seulement des id de tronçons, mais je dois rater quelque chose.

**Comment by odorie** [comment]
L'export des groupes IGN contient bien un identifiant : c'est le champ id_pseudo_fpb (identifiant des voies/lieux-dits du SGA).

**Comment by cquest** [comment]
Les id_pseudo_fpb identiques au code fantoir sont dans le champ fantoir.
Par contre ceux différents (contenant un #) n'ont pas été importés.
Il semble qu'un grand nombre de id_pseudo_fbp avec # existent bien dans fantoir avec le même libellé.
J'ai pu le constater sur ma commune (Saint-Maur-des-Fossés, insee 94068).
Il y a sur cette commune 47 "group" avec un id_pseudo_fpb non rapproché de fantoir (contenant un #).
J'en compte manuellement 25 qui n'ont effectivement pas d'équivalent, mais 22 rapprochables.
Exemple:
94068#003 > 940687212
94068#005 > 940687226
94068#00K > 940688217
94068#00O > 940680118
94068#00P > 940684745
94068#00Q > 940687172
etc...

Est-ce que le référentiel fantoir complet est utilisé dans les traitements faits en amont par l'IGN ?
J'ai l'impression que soit il est ancien (la rue de Cayeux est assez récente) ou que les infos manques pour les voies sans numéros (cas de pas mal de places, squares, passages).

Je tente un rapprochement automatique, après prise en compte des abréviations qui sont différentes.

**Comment by odorie** [comment]
Pour rapprocher les voies/Lieux-dits IGN (export SGA/BDUni du 10 juillet) et les voies/lieux-dits DGFIP, il ne faudrait pas utiliser le champ id_pseudo_fpb de ce fichier, mais plutôt la concaténation des champs code_insee et id_fantoir de ce fichier.

Le champ id_pseudo_fpb est champ interne IGN qui peut ne rien avoir à voir avec le fantoir (par exemple quand la voie est apparu dans la base IGN, avant qu'on intègre la voie DGFIP, l'IGN créé un id_pseudo_fpb avec un #. Ce champ n'est pas mis à jour par l'IGN à l'intégration du fantoir contrairement au champ id_fantoir. Idem pour les mises à jour de voies).

Par contre, le champ id_pseudo_fpb sert d'identifiant IGN et nous aimerions que le champ ign des groupes ban soit rempli avec celui-ci.

D'autre part le champ id_fantoirs du fichier csv contient les rapprochements 1->n (n > 1) de voies IGN/DGFIP. Comment les intégrer à l'init ban ?

Pour les 2 dernières questions (date du référentiel fantoir utilisé par l'IGN et est ce qu'il est chargé complètement), je me renseigne ...

**Comment by cquest** [comment]
Oups, effectivement j'étais passé à côté de cette différence entre id_pseudo_fpb et id_fantoir, je comprends mieux.
Du coup, il y a 300738 group sans id_fantoir et on peut en rapprocher une partie de fantoir. 
Sur la France entière, j'arrive à en rapprocher assez facilement 76913 (1542 pour le 33).

Voici le résultat:
[rapprochement_groups_ign_fantoir.zip](https://github.com/BaseAdresseNationale/ban/files/464152/rapprochement_groups_ign_fantoir.zip)

**Comment by cquest** [comment]
Deuxième passe de rapprochement, cette fois-ci sur les lieux-dits.
31285 se font facilement, sur la base du nom ou nom_afnor.
[rapprochement_lieux-dits.csv.gz](https://github.com/BaseAdresseNationale/ban/files/469988/rapprochement_lieux-dits.csv.gz)

On passe sous les 200.000.

**Comment by cquest** [comment]
J'ai fait un rapprochement sur les lieux-dits qui portent des suffixes "NORD/SUD/EST/OUEST" dans FANTOIR... 32150 de moins.

192874...

**Comment by cquest** [comment]
Je reviens à l'issue initiale (id IGN manquant)... c'est en principe réglé à par quelques exceptions à analyser. Je passe le relais aux recetteurs ;)

**Comment by odorie** [comment]
Je confirme que c'est bon concernant le remplissage de ce champ dans le dernier dump du 21/09. 
Il y a encore quelques groupes IGN manquants à l'appel ou quelques différences sémantiques, mais c'est l'objet d'autres tickets.
Je ferme ce ticket.
