### ISSUE TITLE
Non remplissage du champ name des positions lors de l'initialisation BAN à partir des exports SGA/BDUni de l'IGN

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#180]
Dans la BAN initialisé fin août, les name de position sont tous vides. Pourtant les données SGA/BDUni envoyées fin juin comprennent des compléments d’adressage à intégrer ici ou dans des groupes secondaires. Ces informations sont dans le champ designation_de_l_entree des fichiers csv housenumber<dep>.

Faut-il intégrer ces données ? (Ceci fait partie d'une question générale sur la mise en oeuvre des compléments d'adressage dans la ban)

**Comment by christopheprudent** [comment]
voici un rapide comptage des différents cas initiés

   kind   |  positioning |  count
----------|-------------|----------:
 segment  | other       |  1102973
 building | other       |    54973
 entrance | other       | 17154129
 unknown  | other       | 21870688

et en interrogeant les données, codées 'building', il n'y a pas d'info de complément d'adresse dans la colonne *Position.name* ?

**Comment by yohanboniface** [comment]
Corrigé côté BAN, mais je crois pas avoir ça dans les données. @cquest je t'affecte le ticket :)

**Comment by odorie** [comment]
Les compléments d'adressage du SGA/IGN n'ont pas été basculés dans l'init du 21 septembre.
Sur les départements du 06 et 33, il y a 11 000 compléments environ dans les données du SGA.
