### ISSUE TITLE
Normalisation du champ attributes->source sur housenumber lors de l'initialisation de la BAN

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#186]
Ce champ est rempli soit en minuscule, soit en majuscule :
"source"=>"COMMUNE DE SAINT-ETIENNE-DE-TINEE (2009-01-01)"
"source"=>"COMMUNE DE SAINT-MARTIN-DU-VAR (2009-01-01)"
"source"=>"Toulouse Métropole (1989-06-01)"
 "source"=>"COMMUNE DE LA ROQUETTE-SUR-VAR (2009-01-01)"
 "source"=>"Rennes Métropole (2014-01-31)"
....

Nous proposons de tout initialiser en majuscules

**Comment by cquest** [comment]
C'est désormais le cas: https://github.com/BaseAdresseNationale/ban/blob/cf383768f2f4eb5cce29ce768a64923e43fe1b98/scripts/init/03_export_json.sql#L316
