### ISSUE TITLE
Faut-il charger tous les lieux-dits du cadastre dans la ban ?

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#189]
Dans la ban initialisée fin août, il semble que l'on retrouve tous les lieux-dits du cadastre dans les groupes, y compris de très anciennes dénominations (dont certaines plus utilisées), des noms de champs, bois ...

En conséquence, on a beaucoup plus de groupes dans la ban (7.5 millions) que dans les données Poste et IGN qui en contiennent entre 3 et 4 millions. Dans ces 2 dernières bases, de nombreux lieux-dits du cadastre ont été filtrés.

Faut-il charger dans la ban tous les lieux-dits du cadastre ?

**Comment by cquest** [comment]
Il me semble que c'est préférable même si ils ne sont pas utilisés actuellement.

Ce n'est pas parce qu'on n'a pas actuellement d'adresse numérotée dans un lieu-dit qu'il ne faudrait pas avoir d'information sur l'existence de ce lieu-dit.
Ceci permet de bien se raccrocher au lieu-dit et à ses identifiants existants sinon on risque de créer un futur doublons et il faudra refaire des rapprochements.

Au final ce n'est pas la partie la plus volumineuse de la base et j'imagine mal la DGFiP s'appuyer à terme sur la BAN si elle ne retrouve pas l'intégralité de FANTOIR.

**Comment by odorie** [comment]
Ma remarque ne concernait pas spécifiquement les lieux-dits sans adresse numéroté. Dans la base IGN, nous avons de nombreux lieux-dits sans adresse numéroté. Mais elle concernait plutôt les lieux-dits non habités parfois obsolètes du cadastre représentant les champs, forêts ...
Mais effectivement les avoir, permet de raccrocher des adresses le jour où elles sont créées.
Et puis le tri est difficile ...

**Comment by parville** [comment]
Bonsoir, puis-je ajouter que ce faisant vous contribuerez à aider à localiser des événements graves dans ces lieux  !

**Comment by odorie** [comment]
Les données chargées correspondent bien aux 7.5 millions de lignes du fantoir.
Effectivement ce n'est pas gênant de les avoir.
Le champ attributes contient 'fantoir:date_annul' pour indiquer les voies/lieux-dits "annulés dans le fantoir.
Cela permet de faire un premier tri.
Du coup je ferme ce ticket, que j'avais ouvert.
