### ISSUE TITLE
Numero null sur les house numbers suite à l'initialisation de la ban

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#195]
Environ 1.6 millions de house numbers ont un numéro null suite à l'initialisation de la BAN.

On avait parlé de créer des numéros null pour les voies sans adresse pour les lier au code postal.

Ce chiffre nous semble important. Mais nous avons peut-être raté quelque chose qui l'expliquerait ?

**Comment by christopheprudent** [comment]
il n'y a pas de souci : toute voie présente dans `Group` possède aussi une occurence dans `Housenumber`, avec number à NULL pour porter

- clé POSTE (CEA) en lien normalement avec le CP (postcode_id)

**Comment by odorie** [comment]
Merci pour ces précisions.
Nous n'avions pas noté que toutes les voies La Poste donnaient une ou n occurrences de Housenumber avec numero null. 
Du coup les utilisateurs de la ban ne risquent-ils pas de se poser quelques questions en voyant arriver ces objets et du coup être tentés de les supprimer ?
La question du traitement/consigne pour ces objets se pose par exemple pour le guichet adresse (nous pourrions par exemple ne pas les faire afficher dans le guichet adresse).

**Comment by christopheprudent** [comment]
à noter aussi par contre que c'est "la" solution pour pouvoir affecter un CP à une voie, 
et donc nécessaire pour les voies non numérotées (quand même + de 35% dans notre référentiel)

**Comment by cquest** [comment]
Je ferme donc vu que c'est normal.
