### ISSUE TITLE
Mauvaises coordonnées dans l'export IGN SGA/BDUNI sur les départements d'Outre Mer

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#200]
Lors de la recette de l'initialisation BAN, nous nous sommes rendu compte que les coordonnées des exports IGN SGA/BDUNI sur les départements d'Outre Mer n'étaient pas corrects.

Les coordonnées dans la BAN sont corrects (car visiblement ces exports n'ont pas servi pour l'initialisation de la ban).

Mais il faudrait que l'IGN corrige ses exports, qui doivent servir à la vrai initialisation ban, plutôt que les exports BAN v0/guichet adresse.

@cquest  ou @yohanboniface, pouvez-vous m'affecter ce ticket ?

**Comment by yohanboniface** [comment]
@odorie je t'ai ajouté à l'orga, tu as dû recevoir une invitation

**Comment by odorie** [comment]
Vu, merci. Du coup, je m'assigne ce ticket.

**Comment by odorie** [comment]
Corrigé dans l'export SGA/BDuni du 18/10
