### ISSUE TITLE
Stockage de la source des données sur les groupes/house numbers en cas de multi-source

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#207]
Pour les positions, les positions de chaque partenaire sont conservées avec le champ source qui précise le nom du partenaire. Exemple : "Rennes Métropole", "DGFIP/BANO", "IGN" ...

Pour les groupes/housenumbers, les données sont fusionnées dans la mesure du possible. Une seule voie "rue de xxx" sur la commune, idem pour les numéros.

Or ces objets proviennent souvent de plusieurs sources (LA POSTE, DGFIP, COMMUNE, AGGLO, BANO ...).

Actuellement la dernière source uniquement est stockée dans le champ "attributes". 
Une simple interrogation du champ "attributes" ne suffit pas pour avoir l'ensemble des sources d'un objet en cas de multi-source.
Pour savoir qu'un group vient de la DGFIP, il faut vérifier que son fantoir est rempli. Pour le house number ?
Pour savoir qu'un group/house number vient de La Poste ou l'IGN, il faut vérifier que les identifiants de ces 2 organismes sont remplis.
Quid des autres organismes ?

Serait-il intéressant de stocker plus de sources dans attributes ou d'avoir un champ dédié plus riche ?

**Comment by cquest** [comment]
Si on a besoin du détail des sources qui permettent d'aboutir à la dernière version d'un objet, il faut se tourner vers les "versions".

Cette table (et les endpoints dédiés de l'API) sont destinés justement à ça car tout conserver dans l'objet est bien trop complexe car il faudra se poser la question sur chaque champ et pas globalement sur l'objet lui même.

Pour les id (dgfip, ign, poste, etc), ils permettent non pas de savoir quelle est la source de l'objet, mais que cet objet était connu de ces différentes sources (et aussi qu'on a pu les apparier).

L'info de "source" dans les attributes est utilisée par le code d'init pour ne pas faire le même travail deux fois (si "source" identique, le code d'init ne fait rien et passe à la suite du fichier à importer).
En théorie, cet attribut pourrait ne pas être conservé au final.

**Comment by odorie** [comment]
Mon ticket était mal formulé et je mélangeais 2 besoins :
- quelles sont les sources ayant contribué à un objet suite à l'initialisation.
- quelles sont les sources ayant contribué à un objet plusieurs mois après l'initialisation quand cette donnée a pu être créée/modifiée en dehors de l'initialisation.

Maintenir cette information dans un champ parait compliquée.

Il faudra effectivement interroger les versions pour avoir cette réponse.

Il peut être intéressant de conserver la trace de la source à l'initiation.

Je ferme ce ticket
