### ISSUE TITLE
limitation route BBOX

### ISSUE THREAD

**Issue by msotgia** [BaseAdresseNationale/ban#213]
Bonjour,

lorsque l'on récupère une liste d'objets le paramètre limit passe automatiquement à 100 si la valeur est supérieure. Cette limitation est gênante pour la route BBOX où l'on récupère des objets pour les afficher sur une carte. On en a donc besoin d'un grand nombre dans pas mal de cas. Pourrait-on augmenter cette valeur à 1000 et faire une exception pour cette route?

**Comment by yohanboniface** [comment]
Oui c'est possible, à avoir après les impacts une fois en prod, mais on a le temps de voir.
Après, je me demande si c'est un service à rendre à l'utilisateur que de lui afficher 1000 objects d'un coup?

**Comment by laurentlabrunie** [comment]
Bonjour,

oui, 1000, çà me conviendrait moi aussi.
Pour ma part, il ne s'agit pas d'afficher 1000 objets d'un coup mais j'ai besoin de récupérer la totalité des objets pour effectuer un traitement dessus et en suite, je pagine à 100 (en gros, c'est un peu plus compliqué). Et j'ai bien besoin de la totalité pour faire le traitement.

J'ai fais des tests pour la récupération des voies de bordeaux (récup et traitement en fait) :
En tout 2500 voies.
pour 20 voies : 48s
pour 100 voies : 13s
pour 1000 voies : 10s

3s, y a pas mort d'homme mais derrière un écran, et si c'est une tache répétitive, ça peut être génant.
1000 me semble un bon compromis et qui peut le plus, peut le moins.
