### ISSUE TITLE
Code fantoir avec des # à l'issue de l'init

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/ban#215]
Suite à l'init du 21 septembre, environ 4 400 groupes ont un code fantoir avec un #. 
Ne devraient-ils pas être vides (reste de l'id pseudo fpb IGN) ?

**Comment by cquest** [comment]
Effectivement is est plus logique qu'il reste vide vu que ce n'est pas un code FANTOIR mais un pseudo.
