### ISSUE TITLE
accès API pour réaliser une redirection (Group)

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/ban#219]
dans l'interface Territoires pour contrôler et valider les voies d'une commune, nous allons avoir besoin de traiter les doublons (regroupement proposé pour leur détection) confirmés de manière interactive

pour chaque regroupement détecté,
- valider l'un d'entre eux, comme étant la voie de référence

- désactiver les autres, ce qui nécessite les actions suivantes:

- [ ] rediriger chacun des doublons confirmés, vers cette voie de référence
*pour cela, ouvrir une nouvelle route dans l'API, du type:*
POST /group/{identifier1}/redirect/{identifier2}

- [ ] effacer ces doublons
DELETE /group/{identifier}

**Comment by yohanboniface** [comment]
related https://github.com/BaseAdresseNationale/ban/issues/83
