### ISSUE TITLE
Ajouter PostCode.complement

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/ban#241]
Pour la ligne 5.

**Comment by yohanboniface** [comment]
@christopheprudent actuellement, on a une contrainte d'unicité sur la paire "code+municipality".
D'après nos discussions d'hier, je comprends qu'après fusion des communes A, B et C, on aura deux codes postaux B et C qui pointeront sur la commune A, avec potentiellement le même code.
Du coup deux options:
- ou bien on s'est trompé/mal compris sur le scénario d'hier
- ou bien il faut faire sauter la contrainte d'unicité

T'en penses quoi?

**Comment by christopheprudent** [comment]
la classe Postcode va intégrer en plus un complément (éventuel), du coup l'unicité porte sur le trio (code+municipality+complement)

**Comment by yohanboniface** [comment]
OK, merci :)

@christopheprudent deux questions:
- longueur max du champ?
- est-ce que ça vaut la peine de vérifier que les valeurs qu'on nous passe pour ce champ sont bien tout en majuscule, sans accent, etc.? Si oui, je veux bien des règles un peu plus précises si t'as :)

**Comment by christopheprudent** [comment]
il s'agit du même contrôle à faire que celui associé à l'attribut 'name'
sur 38 caractères max, en libellé non accentué, en majuscule

par contre, je n'ai pas les RG d’abréviation (norme) de ce genre de libellé (fait dans la base RAN)

**Comment by yohanboniface** [comment]
> il s'agit du même contrôle à faire que celui associé à l'attribut 'name'
sur 38 caractères max, en libellé non accentué, en majuscule

Est-ce que tu veux un contrôle au moment de la validation des données (i.e. on vérifie que la chaîne correspond aux specs, si c'est pas le cas on renvoie une erreur), ou bien est-ce que veux un traitement pour la mettre aux normes si elle ne l'est pas?

> par contre, je n'ai pas les RG d’abréviation (norme) de ce genre de libellé (fait dans la base RAN)

OK, tu me diras si y a des règles à ajouter.

**Comment by christopheprudent** [comment]
salut, non ce n'est pas la peine, je pense, car cette entité est gérée par LA POSTE, et donc mise à jour avec nos libellés normés, pas de surcharge à faire dans l'API  :stuck_out_tongue_winking_eye:

**Comment by christopheprudent** [comment]
en cas de fusion des communes A et B (vers A au final)
une RG est de créer un complément Postcode B sur le même CP (avant la fusion) avec A comme libellé, **SI** le libellé B n'est pas inclus dans celui de A (après fusion)

ATTENTION au cas où la nom de la commune A (après fusion) est égal à celui de B !
ex: communes ST BON TARENTAISE et COURCHEVEL (déjà complément L5 de ST BON TARENTAISE dans le référentiel RAN)
je cherche en interne le résultat attendu, et je te tiens au courant...

**Comment by christopheprudent** [comment]
prenons l'exemple des communes ST BON TARENTAISE (73277) mono-CP (73120), LA PERRIERE (73198) multi-CP (73120, 73600), qui vont fusionner pour donner la commune COURCHEVEL (73277)

- 1er cas (sans changement de CP)

L5|CP|L6|►|L5|CP|L6
---|---|---|---|---|---|---|---
COURCHEVEL|73120|ST BON TARENTAISE||||
  |73120|ST BON TARENTAISE||ST BON TARENTAISE|73120|COURCHEVEL
  |73120|LA PERRIERE||LA PERRIERE|73120|COURCHEVEL
  |73600|LA PERRIERE||LA PERRIERE|73600|COURCHEVEL


- 2e cas (au passage, la demande est aussi d'annuler aussi le  CP 73600)

L5|CP|L6|►|L5|CP|L6
---|---|---|---|---|---|---|---
COURCHEVEL|73120|ST BON TARENTAISE||||
  |73120|ST BON TARENTAISE||ST BON TARENTAISE|73120|COURCHEVEL
  |73120|LA PERRIERE||LA PERRIERE|73120|COURCHEVEL
  |73600|LA PERRIERE||||

dans tous les cas, le Postcode d'origine avec COURCHEVEL en L5 est désactivé (heureusement, il ne porte pas d'attachement de voies, sinon à rattacher également...)
dans le 2e cas, il est nécessaire de rattacher les voies et numéros du CP 73600 (à annuler sur cette commune) au CP 73120 restant; puis de désactiver aussi le Postcode avec LA PERRIERE et ce CP 73600

2 solutions sont envisageables, pour les Housenumber concernés (voie avec number à NULL, et numéro)
sans redirection: le lien postcode_id est mis à jour directement
avec redirection: création d'un nouveau Housenumber en lien avec CP 73120, et redirection ancien Housenumber vers ce nouveau

une préférence ?
et aussi, je me demande comment faire avec l'API la solution sans redirection ?

**Comment by yohanboniface** [comment]
@christopheprudent je comprends pas bien pourquoi tu donnes deux cas, lequel doit-on implémenter? :)
C'est toi "monsieur La Poste", c'est toi qui dois nous dire ce qu'on doit faire ;)

> avec redirection: création d'un nouveau Housenumber en lien avec CP 73120, et redirection ancien Housenumber vers ce nouveau

Pour moi il ne faut pas de redirection côté housenumber: le housenumber ne change pas lui-même, on met juste à jour le lien vers le code postal éventuellement (souvent on va juste rajouter la ligne 5, si j'ai bien compris).

**Comment by christopheprudent** [comment]
c'était pour faire un exemple de fusion, avec plusieurs CP, ce que j'avais cru comprendre comme demande :)
sinon, oui, LA POSTE donnera le choix parmi ces 2 cas, pas de souci :grinning:

ok, pas de redirection,
comment faire alors avec l'appel API, aurais-tu la syntaxe de l'appel à faire ?  pour changer ce lien (postcode_id) d'un Housenumber

ex: requête patch 
http://ban_url/housenumber/ban_hn_id/postcode=(complement, code, name) ???

**Comment by yohanboniface** [comment]
> c'était pour faire un exemple de fusion, avec plusieurs CP, ce que j'avais cru comprendre comme demande :)

Oui, c'est top :)
Mais ma question portait sur le fait que tu détailles deux cas, alors qu'il me semble on ne va en implémenter qu'un, donc on doit savoir lequel :)
Il faut qu'on parte sur le cas générique je dirais. S'il y a des traitements particuliers (la suppression d'un code postal me semble en être un, mais je peux me tromper), il faudra ou bien une autre commande dédiée, qu'on lançerait par la suite; ou bien un outil côté Poste qui ferait ça via l'API (je parle bien seulement des cas particuliers).


>  comment faire alors avec l'appel API, aurais-tu la syntaxe de l'appel à faire ? pour changer ce lien (postcode_id) d'un Housenumber

Oui, tu fais un PATCH sur le housenumber, et tu passes en body:

    {
        "postcode": "xxxx",
        "version": 2
    }

Où "xxx" est l'id du nouveau PostCode bien sûr. Quant au numéro de version, il faut que ce soit +1 par rapport à la version de départ.

A noter donc que ces changements seront pris en charge par le script de fusion de commune, donc en théorie, sauf cas particulier, la Poste n'aura pas à faire d'appel API pour cela.

**Comment by christopheprudent** [comment]
merci pour le détail de la requête API, tu donnes donc en argument l'id BAN du Postcode (et non ses attributs), à récupérer par ex via la liste des Postcodes d'une Municipality
et c'est l'API qui se charge de traduire ce BAN-id en pk pour la base?

sinon, en effet, l'outil de fusion devrait prendre en charge le niveau générique d'une fusion
et un nouvel outil LA POSTE devra s'occuper de ces changements de CP (qui se sont également produit sans parler de fusion d'ailleurs, donc ce qui milite bien pour un autre outil)

**Comment by yohanboniface** [comment]
> merci pour le détail de la requête API, tu donnes donc en argument l'id BAN du Postcode (et non ses attributs), à récupérer par ex via la liste des Postcodes d'une Municipality
et c'est l'API qui se charge de traduire ce BAN-id en pk pour la base?

Affirmatif :)

**Comment by christopheprudent** [comment]
ok, 
petite note pour recenser les RG, que cet outil devra appliquer:

- pour tous les Housenumbers, mettre à jour le lien CP (postcode_id), et version n+1

- pour les voies,

  mono-CP : de même, mettre à jour le lien CP, et version n+1
  multi-CP : désactiver la voie sur l'ancien CP, et rediriger celle-ci sur la voie de l'autre CP

  ex: rue 'CHAMP GREFFON' sur les 2 CP (73120, 73600 celui-ci à annuler) de la commune LA PERRIERE
  désactiver le Housenumber (number à NULL) sur CP 73600
  rediriger le Housenumber (number à NULL) sur CP 73600 vers le Housenumber (number à NULL) sur CP 73120, pour la clé LAPOSTE (CEA)

**Comment by yohanboniface** [comment]
> désactiver le Housenumber (number à NULL) sur CP 73600
rediriger le Housenumber (number à NULL) sur CP 73600 vers le Housenumber (number à NULL) sur CP 73120, pour la clé LAPOSTE (CEA)

Pourquoi ne pas mettre à jour le lien là aussi?

**Comment by christopheprudent** [comment]
parce qu'il va faire doublon 
aujourd'hui, nous avons en fait 1 voie 'CHAMP GREFFON' distribuée par 2 CP, chaque portion ayant son CEA propre

voie | matricule|CEA | CP
-----|----------|-----|----
CHAMP GREFFON|3320912|7319822227|73120
CHAMP GREFFON|3320912|7319822234|73600

ce qui se traduit dans la BAN, en 2 tuples Housenumber avec number à NULL, pour stocker ces 2 CEA et postcode_id pour les différencier

si tu modifies le lien 73600 en 73120, tu vas obtenir un doublon, avec 2 CEA différents
ce CEA 7319822234 est à désactiver, et doit pointé sur le CEA 7319822227

tu penses y voir un souci ?

**Comment by yohanboniface** [comment]
Humm, on parle peut-être pas du même outil en fait :)
Tu fais référence à l'outil Poste pour annuler un CP? Moi j'étais resté sur l'outil de fusion de commune :s

**Comment by christopheprudent** [comment]
oui, tu as raison, c'est pour l'outil d'annulation de CP, brr, désolé!
