### ISSUE TITLE
Principe de composition des id

### ISSUE THREAD

**Issue by MaelREBOUX** [BaseAdresseNationale/ban#40]
Bonjour,

Tous les objets du MCD sont identifiés par :
- leur id
- leur version

L'id qui aura le rôle d'identifiant unique sera-t-il un "bête" incrément (style sequence postgreSQL) ou qqch de plus normé à l'instar des uuid, cf https://fr.wikipedia.org/wiki/Universal_Unique_Identifier) ?

**Comment by yohanboniface** [comment]
Pour l'instant c'est un «bête» incrément, table par table, mais la réflexion est ouverte, et l'uuid est dans le radar.

**Comment by MaelREBOUX** [comment]
OK.
On est d'accord que si on modifie les attributs d'un enregistrement (voie ou adresse) :
- son id ne change pas
- sa version est incrémentée
?

**Comment by yohanboniface** [comment]
Absolument. :)

**Comment by MaelREBOUX** [comment]
Logique. A mettre sur le wiki alors.

**Comment by yohanboniface** [comment]
cf #90
