### ISSUE TITLE
[MCD] Fusionner Locality et Street ?

### ISSUE THREAD

**Issue by MaelREBOUX** [BaseAdresseNationale/ban#43]
Discussion à lier à #15 #14 et #42 

Actuellement, la traduction qui a été donnée de "Locality" est "lieu-dit".
Mais d'après ce qu'on en a compris, cette classe est censée regrouper : 
 1. les “vrais” lieux-dits avec adresses et/ou les zones d’agrégation d’adresses (ex : zone industrielle)
 2. les lieux-dits sans adresses

Cela peut constituer un mécanisme de compensation intéressant dans les territoires où les communes ne se sont pas encore organisées pour la gestion de bases voies-adresses. Comme la BAN ne gère pas la géométrie des voies, cela nous permet  de remonter dans cette classe l’existence (et la dénomination officielle) de lieux-dits sans adresses.

A relire la spécification de données INSPIRE, j'ai l'impression que ce concept est très proche du concept de **AdressAreaName** :

*An address component which represents the name of a geographic area or locality that groups a number of addressable objects for addressing purposes, without being an administrative unit.*

*NOTE 1 In some countries and regions an address area is a true subdivision of an administrative unit (most often a municipality), so that every address area is fully inside the municipality and so that every part of the municipality is within an address area. In other countries, the concept of address area names is less strict and based on local tradition or specific needs.*

*NOTE 2 In some situations an address area name is not required to obtain unambiguousness; instead the purpose is to make the complete address more informative and descriptive, adding a well known place name (e.g. of a village or community) to the address. This is particularly useful if the municipality or post code covers a large area.*

**Autrement dit, si on dispose d'un lieu-dit avec numérotation, ne conviendrait-il pas de basculer cette voie dans la classe "Street" car elle se comporte exactement comme une voie classique ? Et réserver ainsi cette classe Locality / AdressArea à ces cas moins normés, les lieux-dits sans adresses et les regroupements d'adresses ?**

**Comment by yohanboniface** [comment]
> Autrement dit, si on dispose d'un lieu-dit avec numérotation, ne conviendrait-il pas de basculer cette voie dans la classe "Street" car elle se comporte exactement comme une voie classique ?

C'est une option. Si on fait ça néanmoins on va devoir typer la table (type=voie ou type=lieu-dit) parce qu'on aura des cas d'usage où on aura besoin de le savoir (par exemple pour l'export addok). En soit ça n'est pas un souci, mais souvent quand on commence comme ça on finit par avoir des traitements spécifiques, et là ça veut dire qu'on s'est trompé.
Mais en l'état j'aime bien cette suggestion.

> Et réserver ainsi cette classe Locality / AdressArea à ces cas moins normés, les lieux-dits sans adresses et les regroupements d'adresses ?

Tout à fait :) C'est le rôle que va jouer la class District (pourquoi par renommer en AddressArea, cc @christopheprudent) discutée dans #14, et je suis en train de bosser dessus justement :)

**Comment by MaelREBOUX** [comment]
> Si on fait ça néanmoins on va devoir typer la table (type=voie ou type=lieu-dit)

A rennes un lieu-dit est tout simplement un type de voie. Au même titre sur rue, impasse, boulevard et bien d'autres choses exotiques (résidence, rabine...). Et ça le fait très bien.
C'est géré comme ça ailleurs également et dans d'autres endroits c'est une classe à part.

Mais je vois le pb par rapport à votre MCD actuel.

**Comment by yohanboniface** [comment]
Pour info, j'ai ajouté la ressource District.

@cquest, @christopheprudent: un avis sur l'idée de merger Locality et Street en une seule table? Je suis personnellement plutôt pour: ça simplifie le modèle il me semble, et la distinction lieu-dit/rue peut se suffire d'une colonne "kind", mais vraisemblablement les deux types ont les mêmes comportements.

Reste à voir, le cas échéant, quel nom pour la ressource, *Street* est peut-être un peu trop dédié à une entité linéaire.

**Comment by yohanboniface** [comment]
Contre-argument pour le merge: le cas où une adresse fait partie à la fois d'une voie et d'un lieu-dit.

**Comment by christopheprudent** [comment]
je prend la discussion en route, mais ça rejoint un peu celle de l'issue #14 

en fait, nous revenons un peu au besoin de hérarchie des adresses
ces zones d'adresse peuvent en effet être hiérarchisées (idée du MCD présenté lors du séminaire de Libourne début novembre)
une adresse peut être une voie (ou un numéro sur cette voie), elle-même dépendant d'une zone plus large (lieu-dit, quartier, ancienne commune, ...), cette dernière zone étant liée à une commune

![ban mcd](https://cloud.githubusercontent.com/assets/15735397/11925989/0cb67f0e-a7c1-11e5-9830-485696b312ba.PNG)

**Comment by yohanboniface** [comment]
> en fait, nous revenons un peu au besoin de hérarchie des adresses
> ces zones d'adresse peuvent en effet être hiérarchisées

Personnellement, je suis pas sûr qu'il faille prendre cette voie, pour deux raisons:
- plus le modèle est hiérarchisé, plus d'infos on aura besoin pour ajouter une adresse (par exemple, si non décide que la voie faire partie d'un quartier, il faut connaître le quartier pour ajouter la voie), donc on augmente le coût de contribution
- les différentes "zones" qui ont été listées comme potentiellement candidates à être incluses dans la BAN sont d'une part relativement mal définies (pas toujours sûr de savoir dans quel "quartier" est telle rue) et d'autre part non hiérarchiques entre elles (un quartier de fait pas partie d'un IRIS ni le contraire).

A mon avis, il faut rester dans un modèle minimal simple et souple, et extensible (i.e. données minimales réduites, et possibilité d'étendre au fur et à mesure que les connaissances sur une adresse évoluent). :)

**Comment by christopheprudent** [comment]
nous pouvons en effet continuer avec le modèle plus simple :)
le fait de hiérarchiser n'oblige pas non plus à renseigner tous les liens prévus, mais de faire pareil, avec le minimum requis (voie + commune) et de l'affiner par la suite, avec les éléments supplémentaires si collectés
pour les zones, je crois que Christian avait limité celles-ci jusqu'à l'empreinte de la commune (pas les supra, de type département, etc), et d'inclure peut-être celles de l'IRIS

en tout cas, la hiérarchie permet de répondre à ces empilements d'appartenance d'une adresse avec plusieurs zones gigognes, du moment bien sûr d'avoir tous ces éléments renseignés ou alors de modifier par la suite une adresse déjà enregistrée

**Comment by MaelREBOUX** [comment]
hiérarchie et quartiers = fausses bonnes idée -> à bannir pcq cela va ajouter une grande confusion dans ce qu'on considère un quartier. Un arrondissement oui, OK.

Moi perso je n'accroche pas à ces besoins de zonage intra ou supra communaux (en dehors arrondissements PLM...). Je suis défavorable au traitement des IRIS dans cette base (pérennité ?). Si cela se fait -> à traiter comme une addressArea au même titre que arrondissement et "lieu-dit" / zone de regroupement.

**Comment by yohanboniface** [comment]
> Je suis défavorable au traitement des IRIS dans cette base (pérennité ?).

De mon point de vue, les IRIS iront dans la BAN si et seulement si l'INSEE y est favorable et s'engage à les maintenir à jour.

**Comment by christopheprudent** [comment]
je ne parlais pas des ARM (municipaux, pour PLM), mais du découpage administratif (comme la notion de canton, il y a aussi la notion d'arrondissement)

ok donc, pour ne pas gérer ces hiéarchies de zones

détail alors, comment gérer la notion de commune globale pour ces communes à arrondissements, PLM dans la BAN ?

**Comment by yohanboniface** [comment]
> détail alors, comment gérer la notion de commune globale pour ces communes à arrondissements, PLM dans la BAN ?

Erf, Bonne question! Grml grml grml. Paris et Paris VIII ont chacun leur code INSEE?

**Comment by MaelREBOUX** [comment]
@yohanboniface 
L'INSEE ne les maintient pas car refuse actuellement (presque ?) tous les redécoupages nécessaires pour tenir compte des évolutions urbaines. Dans plusieurs métropoles nous avons des cas de zones IRIS coupant des immeubles récents ou agrégeant trop de population / logements par rapport à ce que cela devrait être.
Si nous disposions d'un autre maillage infra communal (carreaux 200m ? mais ils bougent) une bonne part des CT l'utiliseraient déjà. Je déconseille déjà utilisation IRIS pour toute analyse sur notre territoire : trop grand et pas à jour (cf http://geobretagne.fr/geonetwork/apps/georchestra/?uuid=df789a3f-9980-4629-95be-50a8b04eac3c)
Autre débat loin du sujet de ce ticket.

Pour les arrondissements : pourquoi ne pas les gérer en tant que commune. C'est déjà comme ça que ça fonctionne dans les faits. Non ?

**Comment by christopheprudent** [comment]
oui les arrondissements ont leur code INSEE propre, et la commune globale un autre
PARIS 1er : 75101
PARIS 2e : 75102
et
PARIS : 75056

**Comment by yohanboniface** [comment]
> en interne POSTE, nous avons besoin des 2 niveaux (ARM et COM globale)

Dans la mesure où cette situation est seulement pour PLM, est-il envisageable de garder ces informations en dur (je dirais out of BAN mais peut-être que ça doit être dans la BAN), afin de ne pas compliquer la modélisation juste pour ces trois cas?

**Comment by yohanboniface** [comment]
(J'ai créé un ticket pour les discussions sur IRIS: #48)

**Comment by christopheprudent** [comment]
c'est une solution, 
à chaque client de la BAN de surcharger ces codes INSEE pour PLM s'il en a besoin (75056, 69123, 13055)

**Comment by christopheprudent** [comment]
au final, ces 2 entités (de même modèle) sont traitées de manière identique, à savoir une voie, au sens large, possèdant ou non des numéros, avec un n° FANTOIR
l'argument de zone non linéaire (pour **Locality**) correspond alors au besoin de la nouvelle entité **District**
un lieu-dit, une fois dénommé (nommage de ses voies), peut alors possèder plusieurs voies : et si ce lieu-dit doit être référencé en tant que quartier de la commune, il pourra alors être déclaré dans l'entité **District**, avec des liens sur ces voies nouvellement créées

la différenciation de ces 2 types de voie (**Street** et **Locality**) est-elle réellement à fournir ? pour quel usage ?
si non, la fusion de ces 2 entités pourra simplifier le modèle sans perte d'information, même sans ajouter un type dans l'entité **Street**

**Comment by yohanboniface** [comment]
> la différenciation de ces 2 types de voie (Street et Locality) est-elle réellement à fournir ? pour quel usage ?

La CIA, toujours :/
En l'état, on utilise la rue ET le lieu-dit éventuels pour définir la CIA ([clé d'interopérabilité de l'adresse](https://github.com/etalab/cle-interoperabilite-adresse)), pour distinguer le cas d'une rue qui aurait deux fois le même housenumber mais dans deux hameaux différents (le cas existe au moins pour le "5 route de Poilly" à "Poilly-sur-Tholon").
Dans l'absolu, je trouverais plus propre de fusionner Street et Locality personnellement, mais pour ça il faut résoudre (ou bien dire que ça fait partie des cas non gérés) le cas "5 route de Poilly".

**Comment by yohanboniface** [comment]
J'ai ouvert un ticket sur la réflexion spécifique à notre dépendance au FANTOIR: #64

**Comment by christopheprudent** [comment]
il s'agit de la même voie (ROUTE DE POILLY), au sein de la commune POILLY SUR THOLON, avec en fait deux numéros 5, même si en plus un  quartier (zone) existe

dans ce cas, je pense qu'il y a un souci d'adressage dans la commune, et que la BAN ne doit pas tordre son modèle pour prendre en compte cette anomalie (fiabilisation à demander en fait auprès de cette mairie!)

**Comment by yohanboniface** [comment]
> la BAN ne doit pas tordre son modèle pour prendre en compte cette anomalie (fiabilisation à demander en fait auprès de cette mairie!)

Peut-on réellement s'en sortir par cette pirouette? :) Personnellement, ça m'arrangerait fort, mais j'en doute. On aura certainement des centaines de cas approchants.

Je trouve intéressante l'idée de profiter de la mise en place de la BAN pour nettoyer les cas trop tordus, mais que fait-on tant que ces cas tordus ne sont pas corrigés?

**Comment by MaelREBOUX** [comment]
> dans ce cas, je pense qu'il y a un souci d'adressage dans la commune, et que la BAN ne doit pas tordre son modèle pour prendre en compte cette anomalie (fiabilisation à demander en fait auprès de cette mairie !)

C'est ce que j'ai dit lors de l'open lab : ce cas est clairement un pb d'adressage qui est du ressort de la mairie. Aucune des recommandations ou bonnes pratiques ne sont appliquées ici. Pas étonnant d'obtenir cette situation.
Il y a 2 n° 5 et bien c'est comme ça et ils doivent exister dans la base avec 2 uuid différents. Les outils de diagnostic du site IGN / La Poste (ou autres) sont là pour identifier ces cas et les faire ressortir.

**Comment by christopheprudent** [comment]
mais d'ailleurs, en tant qu'adresse ou mieux en terme de lieu, il ne s'agit pas d'un doublon sachant que la position (x, y) est bien différent dans les 2 cas! le numéro/extension n'est qu'un attribut de ce lieu numéroté, et cet attribut peut être multiple au même titre que le libellé voie, pour le cas de 2 voies homonymes

**Comment by MaelREBOUX** [comment]
Tout à fait : la numérotation déconne mais ce sont 2 adresses (qui désigne une habitation d'ailleurs) avec des positions différentes.
Ca disparaîtra dès que le conseil municipal aura renommer cette voie au sud de la commune.

**Comment by yohanboniface** [comment]
> Il y a 2 n° 5 et bien c'est comme ça et ils doivent exister dans la base avec 2 uuid différents.

Ce n'est pas si simple: ce sont deux adresses, et tout le monde est d'accord pour dire qu'elles doivent exister chacune séparément.
Le problème, c'est la contrainte que ça fait peser sur la modélisation: si on adapte la modélisation pour accepter ce genre de situation (c'est le cas aujourd'hui), on se prive, d'une part, des contraintes en base permettant d'éviter des doublons, on  fragilise, d'autre part, la CIA (obligé d'intégrer la rue ET le lieu-dit).

Et, pour en revenir à la question central de ce ticket: si on merge Street et Locality, on n'a plus de moyen de distinguer sémantiquement ces deux adresses l'une de l'autre (sans regarder leur id ou leur lon/lat, donc).

Bref, je suis personnellement plutôt partant pour faire le merge, mais quid de ces cas de figure? On accepte de ne plus pouvoir les distinguer et elles ne seraient pas accessibles via CIA (parce qu'elles auraient la même clé)?

**Comment by christopheprudent** [comment]
oui pour la non différenciation littérale, exceptée si le terrain permet d'enrichir cette adresse avec le libellé **District** éventuel, 
j'ai regardé GoogleMaps  il y a un cas sur les 2 avec peut-être le "quartier" Auvergne

soit:

Adresse 1|Adresse 2
------------|-------------
5 route de Poilly, 89110 Poilly sur Thonon|5 route de Poilly, **Auvergne**, 89110 Poilly sur Thonon

au final, ces 2 adresses possèdent en effet le même CIA, ce qui permettra de lancer une requête de fiabilisation auprès de la mairie

**Comment by yohanboniface** [comment]
Fait via la class `Group`.
