### ISSUE TITLE
Contrôle des objets par l'API

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/ban#58]
Pour assurer la cohérence de la base, quels contrôles doit effectuer l’API :
o	à la création d’objet ? Contrôle de doublons pour éviter de créer une adresse en double, un localisant d’un même type en double …
o	idem à la modification ?
o	idem pour la suppression/désactivation : contrôle de l’existence d’adresses en cas de désactivation d’une voie ?...

**Comment by yohanboniface** [comment]
Un certain nombre de ces contrôles sont assurés par les contraintes en base (cf #29), il y a quelques contrôles spécifiques comme le fait de vérifier qu'un code postal est bien sur 5 chiffres ou qu'on a pas deux fois le même numéro dans la même rue et le même lieu-dit.
Je dirais que si on veut avancer, il vaut mieux lister les contrôles qu'on veut implémenter, voire créer un ticket pour chacun.

**Comment by ebuard** [comment]
on verra à la réunion de libourne du coup?

**Comment by yohanboniface** [comment]
> on verra à la réunion de libourne du coup?

Pas sûr qu'on ait le temps, on a des gros morceaux à mâcher sur la modélisation ;)

**Comment by ebuard** [comment]
Du coup, faut-il créer une API spécialement centrée sur les contrôles de données à effectuer? L'API de gestion pourrait communiquer avec l'API de contrôle en écriture: l'API de contrôle serait un sas de contrôle pour l'API de gestion.
Je me demande aussi si cette API de contrôle vient taper dans les bases de l'IGN et de La Poste, pour mettre en place des outils de contrôles (en particulier les contrôles terrain par les postiers et les collecteurs).

**Comment by yohanboniface** [comment]
@ebuard je suis d'avis de fermer ce ticket, et ouvrir des tickets spécifiques s'il y a des contrôles qu'on veut implémenter.

**Comment by odorie** [comment]
Après discussion avec @ebuard, nous fermons ce ticket.
Comme indiqué par @yohanboniface, nous en ouvrirons des plus précis quand le besoin s'en fera sentir.
