### ISSUE TITLE
géolocalisation, CP, CEA pour une Voie

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/ban#65]
la géolocalisation est liée dans le modèle BAN à l'entité **Housenumber**, 
la clé POSTE a été rangée dans cette entité
le lien vers le code postal a été rangé dans cette entité; par contre, le CP est porté par la Voie, dans le cas d'une voie non numérotée

:information_source: à noter qu'il existe des voies non numérotées multi-CP (voir https://github.com/etalab/ban/wiki/liste-d%27adresses-type cas 5), et dans ce cas, la voie a autant de CEA que de CP

astuce: 
 il faudrait donc créer autant de lignes avec numéro à 0, avec liens *postcode_id* sur chaque CP
 cela nécessite d'intégrer le CP dans le calcul CIA pour en garantir l'unicité

**Comment by yohanboniface** [comment]
Cf #41
