### ISSUE TITLE
erreur gestion utilisateur sur insertion données (Street, ...)

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/ban#70]
sur insertion de données dans la BAN
**ban import:oldban datafile**

il y a un souci sur la gestion de d'ID de l'utilisateur, qui est incrémenté à chaque insertion
ex:
![ban_error_user](https://cloud.githubusercontent.com/assets/15735397/12318607/cfb14452-ba9b-11e5-9964-c2aec008e780.png)

**Comment by yohanboniface** [comment]
C'est l'id de la session. Mais oui, il faudrait que ce soit la même session tout du long.
