### ISSUE TITLE
Soft delete objects

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/ban#81]
Instead of hard deleting objects, we want to keep them with a deleted status that make them invisible for listings, but still available on GET.
We also want to keep the deleted_date.
Maybe we want a hard-delete endpoint only available for superadmin, in case we really want to delete an object (many duplicates created by mistake, whatever scenario like this); but maybe not, and this could be done from command line only.

**Comment by jrsales** [comment]
Maybe this needs to be put in relation with [https://github.com/etalab/ban/issues/84](url) this issue.
If we consider deleting a version of an address, we should consider always having a more recent version of that address with the same flag(s), otherwise we could remove the only flagged version required by a client, despite having unflagged, more recent, versions.
If we consider deleting an address itself, and thus all of its versions, our best way should indeed be to hide that address.

**Comment by cquest** [comment]
This looks like the "redaction" mechanism used by OSM. Some data can become completely hidden thru the API, missing in all dumps, diffs, etc. This is required to remove copyrighted data, and has been used a lot when OSM switched from CC-by-SA to ODbL licence to remove around 1% of the whole database content.
Such a mechanism seems necessary but its access must be limited to a very small set of admin.

**Comment by yohanboniface** [comment]
- add a `status` column in `ResourceModel` with valid values `visible`, `deleted`
- add a `visible` (name?) classmethod to `ResourceModel` that would act as a wrapper to `select` but adding `status != 'deleted'` to the `where` clause
- adapt every http API (`resources.py`) and `export` command code to use the `visible` method, but not on the GET endpoint, because we still want the object to be accessible there
- adapt all the `unique` field to be `unique_together` with the `status` column
- make sure we create diff when we delete
- add unittests
- do we want to prevent deleting a flagged version? I'd say no because I feel like keeping working with flagged version will be done through mirrored db

**Comment by yohanboniface** [comment]
> add a status column in ResourceModel with valid values visible, deleted 

Instead, add a `deleted_at` column, null by default.

**Comment by yohanboniface** [comment]
Aujourd'hui, quand on fait un delete, si une FK pointe sur l'objet, on va raise une erreur et annuler l'action.
Par exemple, si on essaie de supprimer une Municipality mais qu'il y a toujours des Group qui pointent dessus.
Ce check est tout simplement fait via les contraintes en base.
Question: est-ce qu'on veut reproduire ce comportement dans le cas du soft delete?

**Comment by christopheprudent** [comment]
tu veux dire que l'effacement des éventuelles données liées est à la charge (ou non) de l'appelant ?
si tu veux effacer une ressource, il faut au préalable effacer les données qui y font référence, ou alors c'est l'API qui s'en charge ???

**Comment by yohanboniface** [comment]
> si tu veux effacer une ressource, il faut au préalable effacer les données qui y font référence, ou alors c'est l'API qui s'en charge ???

En l'état, c'est à la charge de l'appelant.
Je pense pas qu'on veuille qu'un DELETE sur municipality/xxx fasse aussi un delete des Group associés, et donc des HouseNumber associés, etc.
Ça me paraît trop risqué, et par ailleurs ce n'est pas le principe du REST mis en place: une URL, une resource.
Tu voudrais qu'on fasse les delete implicites aussi?

**Comment by christopheprudent** [comment]
non, je pense aussi qu'effacer une ressource nécessite quelques précautions
de plus cette action quand même assez rare, 
ok avec ce principe

**Comment by cquest** [comment]
Il me semble que renvoyer une erreur évite de mettre la base dans un état incohérent (soft ou hard delete).
Pas chaud du tout pour les DELETE en cascade, c'est trop dangereux et pas orthodoxe REST.

**Comment by yohanboniface** [comment]
On a quand même un point délicat: la gestion des colonnes (ou groupes de colonnes) uniques.

Prenons ce scénario très simple:

- un objet X dans la base existe avec un FANTOIR `010001234`
- on soft delete cet object, donc il n'est plus visible, mais il existe toujours en base
- quelqu'un veut créer un group avec ce même FANTOIR; la base va retourner une erreur, mais ce ne sera pas évident à comprendre pour l'utilisateur, puisque le premier objet n'existe pas pour lui

Je pense qu'il ne faut pas chercher à contourner les contraintes de BDD, et les garder telles qu'elles sont actuellement, et donc le scénario décrit ci-dessus échouerait. Mais il faut rendre ça compréhensible.

Ce que je propose:
- par défaut, les objets deleted ne remontent pas dans les collections
- on ajoute un paramètre aux collections, genre `status=all` ou `is_deleted=1` qui permet d'inclure les deleted
- quand quelqu'un crée ou modifie un objet et entre en conflit avec un objet deleted, on ajoute un pointeur vers l'objet en question dans le message d'erreur
- on permet les GET sur les objets deleted

Et question suivante et subsidiaire: il faut pouvoir "restaurer" un objet deleted, mais il n'existe pas de verbe UNDELETE en http :p
Qu'elle convention utiliser? Un PUT sans body? Je vais regarder ce qui se fait autour.

Des avis sur tout ça? :)

**Comment by yohanboniface** [comment]
> Qu'elle convention utiliser?

Plusieurs options dans le radar:

- faire un PATCH qui modified `deleted_at`
- faire un PUT
- avoir une route spécifique /resource/{id}/restore

J'aime pas trop la dernière option, parce ce qu'elle est pas en ligne avec le reste de l'API.

J'aime bien l'option 2, parce que ça peut nous permettre d'avoir des `scope` OAuth dédiés tout restant sur le plan de les gérer par couple resource/verb.
Donc par exemple, on pourrait n'autoriser que La Poste à faire des DELETE et des PUT sur PostCode.
Par contre, le PUT == restore (quand la resource est deleted) est pas très implicite.

L'option 1 est pas mal aussi, peut-être la plus explicite, mais ça demande un traitement particulier pour gérer les droits de la suppression/restauration.

Des avis? D'autres idées?

**Comment by christopheprudent** [comment]
DELETE pour effacer une ressource (soft)
et éventuellement PATCH/PUT pour la restaurer ?
dans ce dernier cas, je ne trouve pas l'un plus évident que l'autre, si ce n'est une docu ç lire avant!

**Comment by yohanboniface** [comment]
>  dans ce dernier cas, je ne trouve pas l'un plus évident que l'autre, si ce n'est une docu à lire avant!

Dans les cas du scénario PATCH, l'utilisateur devrait lui-même changer la valeur de `deleted_at`. (ou on pourrait dans ce cas avoir un `status=deleted` ou `deleted=true` pour que ce soit plus facile à manipuler.

**Comment by davidbgk** [comment]
Je garderais le DELETE pour le hard delete (en cascade) réservé aux admins et un PUT/PATCH sur `deleted_at` pour faire du soft avec possibilité de filtrer dessus facilement.

**Comment by yohanboniface** [comment]
> un PUT/PATCH sur deleted_at pour faire du soft

Tu soulèves une bonne question: veut-on une route pour hard delete depuis l'API? La réponse est sûrement oui.
Mais je pense qu'on veut aussi pouvoir gérer les droits sur du soft delete (par exemple pour Municipality). Ce qui voudrait dire avoir une gestion de droit propriété par propriété, ce qu'on essaie d'éviter pour cause d'odeur de gaz.

**Comment by yohanboniface** [comment]
Autre petit point à garder en tête: si on doit autoriser le PATCH ou POST pour restaurer une resource, ça veut dire que quelqu'un pourra patcher une resource deleted sans pour autant la restaurer. Ou bien qu'il faut avoir un bout de code qui empêche spécifiquement ça tout en autorisant à patcher la propriété `deleted_at`, mais bof.

**Comment by yohanboniface** [comment]
Autre question: est-ce que ça fait sens de retourner une "410 GONE" (au lieu de 404) pour un appel sur un objet deleted?

**Comment by davidbgk** [comment]
Oui mais soft ou hard ? :)

**Comment by davidbgk** [comment]
Après discussion avec @yohanboniface :

* le hard delete ne se fait pas via l'API mais en ligne de commande
* l'utilisateur souhaitant supprimer une ressources fait un `DELETE` sur `/resource/{id}` et récupère une `204`
* l'utilisateur souhaitant vérifier l'état d'une ressource supprimée fait un `GET` sur `/resource/{id}` et récupère une `410` **mais** également le contenu de la ressource supprimée dans le `body` (TODO: vérifier la compatibilité avec la spec HTTP)
* l'utilisateur souhaitant créer une ressource qui a existée fait un `POST` sur `/resource` et se prend une `409` lui indiquant un conflit avec `/resource/{id}` dans le body
* l'utilisateur souhaitant restaurer la ressource fait un `PUT` sur `/resource/{id}` avec le contenu enrichi d'une version supérieure à celle qu'il a pu consulter avec le `GET 410`

Les éléments supprimés n'apparaissent plus dans les listes, il faut explicitement faire un `GET` sur `/resource/{id}` afin de récupérer l'ancien contenu.

**Comment by yohanboniface** [comment]
J'ajoute un point: le hard delete ne serait possible que via une ligne de commande.
Le scénario qu'on cherche à couvrir avec le hard delete, c'est par exemple des objets créés par erreur.
Et on ne fait pas un endpoint spécifique, pour tâcher de garder la signature de l'API simple, partant du principe que le hard delete sera l'exception et sera strictement opérée par l'équipe technique.

**Comment by odorie** [comment]
Je trouve votre proposition très bien. Le hard delete sera très rare et vraiment réservé à des cas particuliers : donc en ligne de commande c'est très bien et ça libère le "DELETE" de l'API pour le soft-delete et on pourra lui mettre des droits spécifiques.
Dans la plupart des cas, on utilisera le soft-delete qui permet de garder trace de l'objet.

**Comment by laurentlabrunie** [comment]
Je pense aussi que la ligne de commande gérée par l'équipe technique est une bonne solution.
Et je pense également que ça devrait être la même chose pour le "restore". Car à moins que je me trompe, l'action de restaurer une ressource serait aussi une exception et ferait suite à une erreur... Y aurait il d'autres cas ? Et faudra t'il garder une trace de la restauration ? Ou supprimer celle du soft delete faite par erreur ?

**Comment by yohanboniface** [comment]
> Et je pense également que ça devrait être la même chose pour le "restore". Car à moins que je me trompe, l'action de restaurer une ressource serait aussi une exception et ferait suite à une erreur... 

Le soft delete et le restaure vont de pair: il faut que ceux qui ont la possibilité de faire un soft delete puissent aussi faire un restaure.
Dans tous les cas, ce seront des droits spécifiques, réservés à un petit nombre d'acteurs pour la plupart des resources.
