### ISSUE TITLE
Ajouter un champ pour le type d'adressage?

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/ban#98]
Doit-on ajouter un champ au modèle Group pour le type d'adressage (classique, métrique, mixte, anarchique), ou bien doit-on utiliser les attributs pour ça?

**Comment by cquest** [comment]
je vois plutôt ça en attribut

**Comment by odorie** [comment]
Suite à la réunion BAN Team d'hier sur le modèle, nous proposons pour ce champ en "clair":
nom du champ : adressing_type
valeurs:

- **Classical** : Un côté de la rue porte des numéros pairs, l’autre des numéros impairs. Les numéros sont ordonnés par ordre croissant ou décroissant le long de la rue.

- **Metric** : Les numéros correspondent à la distance entre leurs positions et le point origine de
la rue. Le principe de côté pair et impair n’est pas toujours conservé.

- **Linear order** : Les numéros sont ordonnés le long de chaque côté de la rue, mais
sans distinction pair ou impair.

- **Mixed** : Le rue comporte 2 types d'adressages différents ("Classical", "Metric", "Linear order"). Cela peut se produire en zone non urbaine où la rue commence en Classique pour terminer en métrique.

- **Anarchical** :  Les numéros ne sont pas ordonnés.

- **"null"** : La rue n'a pas de numéro ou le type d'adressage n'est pas connu. Valeur par défaut pour les groupes de type "Area"

je n'ai pas trouvé de référence à ce champ dans le thème adresse d'INSPIRE.

Faut-il mettre des contraintes/ contrôle dans l'API pour imposer la valeur nulle sur ce champ pour les groupes de type "Area" ? Je dirais plutôt non, car je ne suis pas sûr qu'il n'y ait pas de cas particulier. On pourrait ajouter ces contraintes/contrôles dans un deuxième temps si besoin.

**Comment by yohanboniface** [comment]
> `adressing_type`

Je pense que `_type` n'apporte pas de valeur ajoutée, j'utiliserais bien tout simplement `adressing`.

>  On pourrait ajouter ces contraintes/contrôles dans un deuxième temps si besoin.

Ça me va très bien comme stratégie :)
