### ISSUE TITLE
Plusieurs Position de même type pour un même housenumber?

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/ban#99]
Doit-on autoriser plusieurs Position avec la même valeur de kind (entrance, parcel, etc.) pour un même housenumber?

A première vue, il est tentant de répondre non. Mais en se penchant sur le problème, c'est, comme toujours, pas si évident.

On a identifié au moins deux cas qui demandent réflexion:
- le cas d'une seule et même adresse pour deux parcelles
- le fait d'avoir les compléments d'adresse dans des objets Position (par exemple, une Position de kind entrance pour chaque "Entrée A", "Entrée B", etc.)

Y a-t-il d'autres cas à joindre à la réflexion?

**Comment by cquest** [comment]
Rien n'empêche d'avoir plusieurs entrées ou plusieurs parcelles pour la même adresse... donc pas d'unicité pour moi.

**Comment by yohanboniface** [comment]
Oui, ou plusieurs bâtiments, etc.
Je ferme.
